parameters:
  - name: serviceConnection
    type: string
  - name: environment
    type: string
  - name: bicepParamFile
    type: string

jobs:
  - deployment: DeployContentApi
    displayName: Deploy Content API
    environment: ${{ parameters.environment }}
    variables:
      templateFile: $(Build.SourcesDirectory)/infrastructure/templates/main-app-release/content-api/content-api-bicep-config.bicep
      paramFile: $(Build.SourcesDirectory)/infrastructure/templates/main-app-release/content-api/parameters/appsettings-${{ parameters.bicepParamFile }}.bicepparam
      bicepConfigDeployName: ContentApiBicepConfig$(Build.BuildNumber)
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self

            - download: MainBuild
              displayName: Download Content API artifact
              artifact: content-api

            - task: AzureCLI@2
              displayName: Content API - Deploy appsettings config Bicep
              inputs:
                azureSubscription: ${{ parameters.serviceConnection }}
                scriptType: bash
                scriptLocation: inlineScript
                inlineScript: |
                  set -e
                  az deployment group create \
                    --name $(bicepConfigDeployName) \
                    --resource-group $(resourceGroupName) \
                    --template-file $(templateFile) \
                    --parameters $(paramFile)

            - template: ../../../../common/ci/tasks/bicep-output-variables.yml
              parameters:
                serviceConnection: ${{ parameters.serviceConnection }}
                deploymentName: $(bicepConfigDeployName)

            - template: ../tasks/deploy-app-service-with-slot.yml
              parameters:
                serviceConnection: ${{ parameters.serviceConnection }}
                displayNamePrefix: Content API
                appName: $(subscription)-as-ees-content
                resourceGroupName: $(resourceGroupName)
                artifactZipPath: $(Pipeline.Workspace)/MainBuild/content-api/GovUk.Education.ExploreEducationStatistics.Content.Api.zip
                appSettingsJson: $(appSettings)
