trigger: none

parameters:
  - name: forceDeployToEnvironment
    displayName: Set to either dev or test to force a deploy to that environment from the chosen branch.
    type: string
    values:
      - none
      - dev
      - test
      - preprod
    default: none

resources:
  pipelines:
    - pipeline: MainBuild
      source: Explore Education Statistics
      trigger:
        branches:
          - dev
          - test
          - master

variables:
  - group: Analytics - Common
  - name: forceDeployToEnvironment
    value: ${{parameters.forceDeployToEnvironment}}
  - name: isDev
    value: $[or(eq(variables['forceDeployToEnvironment'], 'dev'), eq(variables['Build.SourceBranch'], 'refs/heads/dev'))]
  - name: isTest
    value: $[or(eq(variables['forceDeployToEnvironment'], 'test'), eq(variables['Build.SourceBranch'], 'refs/heads/test'))]
  - name: isPreProd
    value: $[or(eq(variables['forceDeployToEnvironment'], 'preprod'), eq(variables['Build.SourceBranch'], 'refs/heads/master'))]
  - name: isMaster
    value: $[eq(variables['Build.SourceBranch'], 'refs/heads/master')]
  - name: vmImageName
    value: ubuntu-latest

pool:
  vmImage: $(vmImageName)

stages:
  - template: stages/deploy.yml
    parameters:
      stageName: DeployDev
      condition: eq(variables.isDev, true)
      environment: Dev
      serviceConnection: $(serviceConnectionDev)
      bicepParamFile: dev

  - template: stages/deploy.yml
    parameters:
      stageName: DeployTest
      condition: eq(variables.isTest, true)
      environment: Test
      serviceConnection: $(serviceConnectionTest)
      bicepParamFile: test

  - template: stages/deploy.yml
    parameters:
      stageName: DeployPreProd
      condition: eq(variables.isPreProd, true)
      environment: Pre-Prod
      serviceConnection: $(serviceConnectionPreProd)
      bicepParamFile: preprod

  - template: stages/deploy.yml
    parameters:
      stageName: DeployProd
      condition:  and(succeeded(), eq(variables.isMaster, true))
      dependsOn: DeployPreProd
      environment: Prod
      serviceConnection: $(serviceConnectionProd)
      bicepParamFile: prod
