trigger: none

parameters:
  - name: deployContainerApp
    displayName: Can we deploy the Container App yet? This is dependent on the PostgreSQL Flexible Server being set up and having users manually added.
    default: true
  - name: updatePsqlFlexibleServer
    displayName: Does the PostgreSQL Flexible Server require any updates? False by default to avoid unnecessarily lengthy deploys.
    default: false
  - name: forceDeployToEnvironment
    displayName: Set to either dev or test to force a deploy to that environment from the chosen branch.
    type: string
    values:
      - none
      - dev
      - test
    default: 'none'

resources:
  pipelines:
    - pipeline: MainBuild
      source: Explore Education Statistics
      trigger:
        branches:
          - dev
          - test
          - master

variables:
  - group: Public API Infrastructure - Common
  - name: forceDeployToEnvironment
    value: ${{parameters.forceDeployToEnvironment}}
  - name: isDev
    value: $[or(eq(variables['forceDeployToEnvironment'], 'dev'), eq(variables['Build.SourceBranch'], 'refs/heads/dev'))]
  - name: isTest
    value: $[or(eq(variables['forceDeployToEnvironment'], 'test'), eq(variables['Build.SourceBranch'], 'refs/heads/test'))]
  - name: isMaster
    value: $[eq(variables['Build.SourceBranch'], 'refs/heads/master')]
  - name: vmImageName
    value: ubuntu-latest
  - name: templateDirectory
    value: $(Build.SourcesDirectory)/infrastructure/templates/public-api
  - name: paramDirectory
    value: $(templateDirectory)/parameters
  - name: upstreamPipelineBuildNumber
    value: $(resources.pipeline.MainBuild.runName)
  - name: deployContainerApp
    value: ${{parameters.deployContainerApp}}
  - name: updatePsqlFlexibleServer
    value: ${{parameters.updatePsqlFlexibleServer}}

pool:
  vmImage: $(vmImageName)

stages:
  - template: stages/deploy.yml
    parameters:
      stageName: DeployDev
      condition: eq(variables.isDev, true)
      environment: Dev
      serviceConnection: $(serviceConnectionDev)
      parameterFile: $(paramDirectory)/main-dev.bicepparam

  - template: stages/deploy.yml
    parameters:
      stageName: DeployTest
      condition: eq(variables.isTest, true)
      dependsOn: DeployDev
      environment: Test
      serviceConnection: $(serviceConnectionTest)
      parameterFile: $(paramDirectory)/main-test.bicepparam

#  - template: stages/deploy.yml
#    parameters:
#      stageName: DeployPreProd
#      condition: eq(variables.isMaster, true)
#      trigger: manual
#      environment: Pre-Prod
#      serviceConnection: $(serviceConnectionPreProd)
#      parameterFile: $(paramDirectory)/main-preprod.bicepparam
#
#  - template: stages/deploy.yml
#    parameters:
#      stageName: DeployProd
#      condition:  and(succeeded(), eq(variables.isMaster, true))
#      trigger: manual
#      dependsOn: DeployPreProd
#      environment: Prod
#      serviceConnection: $(serviceConnectionProd)
#      parameterFile: $(paramDirectory)/main-prod.bicepparam
