variables:
  SPN_NAME: s101d-datahub-spn-ees-dfe-gov-uk
schedules:
- cron: 0 6 * * 1,2,3,4,5
  branches:
    include:
    - dev
  always: true

pr: none

name: $(date:yyyyMMdd)$(rev:.r)
resources:
  repositories:
  - repository: self
    type: git
    ref: refs/heads/dev

jobs:
- template: azure-pipelines-run-ui-test-suite.yml
  parameters:
    jobName: Public
    displayName: Public suite - Robot UI tests
    testFolder: tests/general_public
    artifactName: test-results-public

- template: azure-pipelines-run-ui-test-suite.yml
  parameters:
    jobName: PublishAndAmend
    displayName: Publish release and amend suites - Robot UI tests
    testFolder: tests/admin_and_public_2
    artifactName: test-results-admin-and-public-2

- template: azure-pipelines-run-ui-test-suite.yml
  parameters:
    jobName: Admin
    displayName: Admin suites - Robot UI tests
    testFolder: tests/admin
    artifactName: test-results-admin

- template: azure-pipelines-run-ui-test-suite.yml
  parameters:
    jobName: AdminAndPublic
    displayName: Admin & public suites - Robot UI tests
    testFolder: tests/admin_and_public
    artifactName: test-results-admin-public

- template: azure-pipelines-run-ui-test-suite.yml
  parameters:
    jobName: PublicAPI
    displayName: Public API suite - Robot UI tests
    testFolder: tests/public_api
    artifactName: test-results-admin-public-api
