variables:
  SPN_NAME: s101d-datahub-spn-ees-dfe-gov-uk
schedules:
- cron: 0 5,7,19 * * 1,2,3,4,5
  branches:
    include:
    - dev
  always: true
pr: none

name: $(date:yyyyMMdd)$(rev:.r)
resources:
  repositories:
  - repository: self
    type: git
    ref: refs/heads/dev

jobs:
- job: 'Public'
  displayName: Public UI tests
  timeoutInMinutes: 160
  cancelTimeoutInMinutes: 10
  condition: succeededOrFailed()
  pool: ees-ubuntu2204-large
  workspace:
    clean: all
  steps:
  - checkout: self
    clean: true
    fetchDepth: 5
    fetchTags: false

  - task: UsePythonVersion@0
    displayName: Use Python 3.10
    timeoutInMinutes: 5
    inputs:
      versionSpec: 3.10

  - task: AzureKeyVault@2
    displayName: 'Azure Key Vault: s101d01-kv-ees-01'
    inputs:
      azureSubscription: $(SPN_NAME)
      KeyVaultName: s101d01-kv-ees-01
      SecretsFilter: ees-test-SLACK-BOT-TOKEN,ees-test-SLACK-TEST-REPORT-WEBHOOK-URL
      RunAsPreJob: true

  - task: PythonScript@0
    displayName: Public UI tests
    inputs:
      scriptPath: tests/robot-tests/scripts/run_tests_pipeline.py
      arguments: --admin-pass "test" --analyst-pass "test" --expiredinvite-pass "test" --noinvite-pass "test" --pendinginvite-pass "test" --env "dev" --file "tests/general_public/" --processes 4 --rerun-attempts 3
      workingDirectory: tests/robot-tests
    env:
      SLACK_BOT_TOKEN: $(ees-test-SLACK-BOT-TOKEN)
      SLACK_TEST_REPORT_WEBHOOK_URL: $(ees-test-SLACK-TEST-REPORT-WEBHOOK-URL)

  - task: PublishTestResults@2
    displayName: Publish Test Results
    condition: succeededOrFailed()
    inputs:
      testResultsFiles: tests/robot-tests/test-results/xunit.xml
      failTaskOnFailedTests: true

  - task: PublishPipelineArtifact@1
    displayName: Publish Test Pipeline Artifact
    condition: succeededOrFailed()
    inputs:
      path: tests/robot-tests/test-results/
      artifactName: test-results-public

- job: 'PublishAndAmend'
  displayName: Publish release and amend suites
  timeoutInMinutes: 160
  cancelTimeoutInMinutes: 10
  condition: succeededOrFailed()
  pool: ees-ubuntu2204-large
  workspace:
    clean: all
  steps:
  - checkout: self
    clean: true
    fetchDepth: 5
    fetchTags: false

  - task: UsePythonVersion@0
    displayName: Use Python 3.10
    timeoutInMinutes: 5
    inputs:
      versionSpec: 3.10

  - task: AzureKeyVault@2
    displayName: 'Azure Key Vault: s101d01-kv-ees-01'
    inputs:
      azureSubscription: $(SPN_NAME)
      KeyVaultName: s101d01-kv-ees-01
      SecretsFilter: ees-test-ADMIN-PASSWORD,ees-test-ANALYST-PASSWORD,ees-test-expiredinvite-password,ees-test-NOINVITE-PASSWORD,ees-test-PENDINGINVITE-PASSWORD,ees-test-SLACK-BOT-TOKEN,ees-test-SLACK-TEST-REPORT-WEBHOOK-URL
      RunAsPreJob: true

  - task: PythonScript@0
    displayName: Publish release and amend UI tests
    condition: succeededOrFailed()
    inputs:
      scriptPath: tests/robot-tests/scripts/run_tests_pipeline.py
      arguments: --admin-pass '"$(ees-test-ADMIN-PASSWORD)"' --analyst-pass '"$(ees-test-ANALYST-PASSWORD)"' --expiredinvite-pass '"$(ees-test-expiredinvite-password)"' --noinvite-pass '"$(ees-test-NOINVITE-PASSWORD)"' --pendinginvite-pass '"$(ees-test-PENDINGINVITE-PASSWORD)"' --env "dev" --file "tests/admin_and_public_2" --processes 4 --rerun-attempts 3
    #  The magic incantation '"$(variable)"'was added by Mark to resolve an issue with Analyst password that contained ampersands.
      workingDirectory: tests/robot-tests
    env:
      SLACK_BOT_TOKEN: $(ees-test-SLACK-BOT-TOKEN)
      SLACK_TEST_REPORT_WEBHOOK_URL: $(ees-test-SLACK-TEST-REPORT-WEBHOOK-URL)

  - task: PublishTestResults@2
    displayName: Publish Test Results
    inputs:
      testResultsFiles: tests/robot-tests/test-results/xunit.xml
      failTaskOnFailedTests: true

  - task: PublishPipelineArtifact@1
    displayName: Publish Pipeline Artifact
    condition: succeededOrFailed()
    inputs:
      path: tests/robot-tests/test-results/
      artifactName: test-results-admin-and-public-2

- job: 'Admin'
  displayName: Admin UI tests
  timeoutInMinutes: 160
  cancelTimeoutInMinutes: 10
  condition: succeededOrFailed()
  pool: ees-ubuntu2204-large
  workspace:
    clean: all
  steps:
  - checkout: self
    clean: true
    fetchDepth: 5
    fetchTags: false

  - task: UsePythonVersion@0
    displayName: Use Python 3.10
    timeoutInMinutes: 5
    inputs:
      versionSpec: 3.10

  - task: AzureKeyVault@2
    displayName: 'Azure Key Vault: s101d01-kv-ees-01'
    inputs:
      azureSubscription: $(SPN_NAME)
      KeyVaultName: s101d01-kv-ees-01
      SecretsFilter: ees-test-ADMIN-PASSWORD,ees-test-ANALYST-PASSWORD,ees-test-expiredinvite-password,ees-test-NOINVITE-PASSWORD,ees-test-PENDINGINVITE-PASSWORD,ees-test-SLACK-BOT-TOKEN,ees-test-SLACK-TEST-REPORT-WEBHOOK-URL
      RunAsPreJob: true

  - task: PythonScript@0
    displayName: Admin UI tests
    condition: succeededOrFailed()
    inputs:
      scriptPath: tests/robot-tests/scripts/run_tests_pipeline.py
      arguments: --admin-pass '"$(ees-test-ADMIN-PASSWORD)"' --analyst-pass '"$(ees-test-ANALYST-PASSWORD)"' --expiredinvite-pass '"$(ees-test-expiredinvite-password)"' --noinvite-pass '"$(ees-test-NOINVITE-PASSWORD)"' --pendinginvite-pass '"$(ees-test-PENDINGINVITE-PASSWORD)"' --env "dev" --file "tests/admin" --processes 4 --rerun-attempts 3
      workingDirectory: tests/robot-tests
    env:
      SLACK_BOT_TOKEN: $(ees-test-SLACK-BOT-TOKEN)
      SLACK_TEST_REPORT_WEBHOOK_URL: $(ees-test-SLACK-TEST-REPORT-WEBHOOK-URL)

  - task: PublishTestResults@2
    displayName: Publish Test Results
    condition: succeededOrFailed()
    inputs:
      testResultsFiles: tests/robot-tests/test-results/xunit.xml
      failTaskOnFailedTests: true

  - task: PublishPipelineArtifact@1
    displayName: Publish Test Pipeline Artifact
    condition: succeededOrFailed()
    inputs:
      path: tests/robot-tests/test-results/
      artifactName: test-results-admin

- job: 'AdminAndPublic'
  displayName: Admin & public suites
  timeoutInMinutes: 160
  cancelTimeoutInMinutes: 10
  condition: succeededOrFailed()
  pool: ees-ubuntu2204-large
  workspace:
    clean: all
  steps:
  - checkout: self
    clean: true
    fetchDepth: 5
    fetchTags: false

  - task: UsePythonVersion@0
    displayName: Use Python 3.10
    timeoutInMinutes: 5
    inputs:
      versionSpec: 3.10

  - task: AzureKeyVault@2
    displayName: 'Azure Key Vault: s101d01-kv-ees-01'
    inputs:
      azureSubscription: $(SPN_NAME)
      KeyVaultName: s101d01-kv-ees-01
      SecretsFilter: ees-test-ADMIN-PASSWORD,ees-test-ANALYST-PASSWORD,ees-test-expiredinvite-password,ees-test-NOINVITE-PASSWORD,ees-test-PENDINGINVITE-PASSWORD,ees-test-SLACK-BOT-TOKEN,ees-test-SLACK-TEST-REPORT-WEBHOOK-URL
      RunAsPreJob: true

  - task: PythonScript@0
    displayName: Admin public UI tests
    inputs:
      scriptPath: tests/robot-tests/scripts/run_tests_pipeline.py
      arguments: --admin-pass '"$(ees-test-ADMIN-PASSWORD)"' --analyst-pass '"$(ees-test-ANALYST-PASSWORD)"' --expiredinvite-pass '"$(ees-test-expiredinvite-password)"' --noinvite-pass '"$(ees-test-NOINVITE-PASSWORD)"' --pendinginvite-pass '"$(ees-test-PENDINGINVITE-PASSWORD)"' --env "dev" --file "tests/admin_and_public" --processes 4 --rerun-attempts 3
      workingDirectory: tests/robot-tests
    env:
      SLACK_BOT_TOKEN: $(ees-test-SLACK-BOT-TOKEN)
      SLACK_TEST_REPORT_WEBHOOK_URL: $(ees-test-SLACK-TEST-REPORT-WEBHOOK-URL)

  - task: PublishTestResults@2
    displayName: Publish Test Results
    inputs:
      testResultsFiles: tests/robot-tests/test-results/xunit.xml
      failTaskOnFailedTests: true

  - task: PublishPipelineArtifact@1
    displayName: Publish Test Pipeline Artifact
    condition: succeededOrFailed()
    inputs:
      path: tests/robot-tests/test-results/
      artifactName: test-results-admin-public

- job: 'Playwrighttest'
  displayName: Playwright UI test
  timeoutInMinutes: 160
  cancelTimeoutInMinutes: 10
  condition: succeededOrFailed()
  pool: ees-ubuntu2204-large
  workspace:
    clean: all
  steps:
  - checkout: self
    clean: true
    fetchDepth: 5
    fetchTags: false

  - task: NodeTool@0
    displayName: Use Node version 16 above
    timeoutInMinutes: 5
    inputs:
      versionSpec: "16.X"

  - script: |
      npm install
      npm run build # or any other build script you have
    displayName: 'Install dependencies and build'

  - task: Cache@2
    inputs:
      key: 'npm | "$(Agent.OS)" | package-lock.json'
      restoreKeys: |
        npm | "$(Agent.OS)"
      path: $(npm_config_cache)
    displayName: 'Cache npm packages'

  - script: |
            npm ci --force
    displayName: "Install dependencies"

  - script: |
            npx playwright install --with-deps
    displayName: "Install Playwright Browsers"

        # runs the playwright tests
  - script: |
            npx playwright test
    displayName: "Run Playwright tests"
    env:
            PUBLIC_URL: $(PUBLIC_URL)
            ADMIN_URL: $(ADMIN_URL)
            ADMIN_EMAIL: $(ADMIN_EMAIL)

  - task: AzureKeyVault@2
    displayName: 'Azure Key Vault: s101d01-kv-ees-01'
    inputs:
      azureSubscription: $(SPN_NAME)
      KeyVaultName: s101d01-kv-ees-01
      SecretsFilter: ees-test-ADMIN-PASSWORD,ees-test-ANALYST-PASSWORD,ees-test-expiredinvite-password,ees-test-NOINVITE-PASSWORD,ees-test-PENDINGINVITE-PASSWORD,ees-test-SLACK-BOT-TOKEN,ees-test-SLACK-TEST-REPORT-WEBHOOK-URL
      RunAsPreJob: true



    # this publishes the html report as an artifact that can then be downloaded
  - publish: $(System.DefaultWorkingDirectory)/playwright-report
    artifact: playwright-report
    condition: always()

    # this publishes the junit formated test results to azure pipelines so they can be displayed and tracked there.
  - task: PublishTestResults@2
    condition: always()
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/playwright-results.xml'
      testRunTitle: 'Playwright Test Results'
