parameters:
  - name: jobName
    type: string
  - name: displayName
    type: string
  - name: testFolder
    type: string
  - name: artifactName
    type: string

jobs:
  - job: ${{ parameters.jobName }}
    displayName: ${{ parameters.displayName }}
    timeoutInMinutes: 160
    cancelTimeoutInMinutes: 10
    condition: succeededOrFailed()
    pool: ees-ubuntu2204-large
    workspace:
      clean: all
    steps:
    - checkout: self
      clean: true
      fetchDepth: 5
      fetchTags: false

    - task: UsePythonVersion@0
      displayName: Use Python 3.10
      timeoutInMinutes: 5
      inputs:
        versionSpec: 3.10

    - task: AzureKeyVault@2
      displayName: Azure Key Vault - s101d01-kv-ees-01
      inputs:
        azureSubscription: $(SPN_NAME)
        KeyVaultName: s101d01-kv-ees-01
        SecretsFilter: ees-test-ADMIN-PASSWORD,ees-test-ANALYST-PASSWORD,ees-test-expiredinvite-password,ees-test-NOINVITE-PASSWORD,ees-test-PENDINGINVITE-PASSWORD,ees-alerts-slackapptoken
        RunAsPreJob: true

    - task: PythonScript@0
      displayName: Run tests
      condition: succeededOrFailed()
      inputs:
        scriptPath: tests/robot-tests/scripts/run_tests_pipeline.py
        arguments: --admin-pass '"$(ees-test-ADMIN-PASSWORD)"' --analyst-pass '"$(ees-test-ANALYST-PASSWORD)"' --expiredinvite-pass '"$(ees-test-expiredinvite-password)"' --noinvite-pass '"$(ees-test-NOINVITE-PASSWORD)"' --pendinginvite-pass '"$(ees-test-PENDINGINVITE-PASSWORD)"' --env "dev" --file "${{ parameters.testFolder }}" --processes 4 --rerun-attempts 3
        # The magic incantation '"$(variable)"'was added by Mark to resolve an issue with Analyst password that contained ampersands.
        workingDirectory: tests/robot-tests
      env:
        SLACK_APP_TOKEN: $(ees-alerts-slackapptoken)

    - task: PublishTestResults@2
      displayName: Publish test results
      inputs:
        testResultsFiles: tests/robot-tests/test-results/xunit.xml
        failTaskOnFailedTests: true

    - task: PublishPipelineArtifact@1
      displayName: Publish pipeline artifact
      condition: succeededOrFailed()
      inputs:
        path: tests/robot-tests/test-results/
        artifactName: ${{ parameters.artifactName }}