parameters:
  - name: serviceConnection
    type: string
  - name: displayNamePrefix
    type: string
  - name: appName
    type: string
  - name: resourceGroupName
    type: string
  - name: artifactZipPath
    type: string
  - name: healthCheckPath
    type: string
    default: /api/health
  - name: appSettingsJson
    type: string
    default: '{}'

steps:
  - template: ../../../../common/ci/tasks/set-appsettings-from-json.yml
    parameters:
      serviceConnection: ${{ parameters.serviceConnection }}
      displayName: ${{ parameters.displayNamePrefix }} - updating production app settings
      appName: ${{ parameters.appName }}
      resourceGroupName: ${{ parameters.resourceGroupName }}
      appSettingsJson: ${{ parameters.appSettingsJson }}

  - task: AzureCLI@2
    displayName: ${{ parameters.displayNamePrefix }} - Deploy code directly to production
    retryCountOnTaskFailure: 3
    inputs:
      azureSubscription: ${{ parameters.serviceConnection }}
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        set -e

        az webapp deploy \
          --name ${{ parameters.appName }} \
          --resource-group ${{ parameters.resourceGroupName }} \
          --type zip \
          --src-path "${{ parameters.artifactZipPath }}"

  # Wait for the app service restart to begin.
  - template: ../../../public-api/ci/tasks/wait-for-endpoint-result.yml
    parameters:
      serviceConnection: ${{ parameters.serviceConnection }}
      displayName: ${{ parameters.displayNamePrefix }} - waiting for the app service in the production slot to begin its restart.
      endpoint: https://${{ parameters.appName }}.azurewebsites.net${{ parameters.healthCheckPath }}
      expectedResult: unavailable
      pollingDelaySeconds: 1
      maxAttempts: 60

  # Wait for the app service restart to complete.
  - template: ../../../public-api/ci/tasks/wait-for-endpoint-result.yml
    parameters:
      serviceConnection: ${{ parameters.serviceConnection }}
      displayName: ${{ parameters.displayNamePrefix }} - waiting for the app service in the production slot to restart and report healthy.
      endpoint: https://${{ parameters.appName }}.azurewebsites.net${{ parameters.healthCheckPath }}
      maxAttempts: 20
