parameters:
  - name: stageName
    type: string
  - name: environment
    type: string
  - name: serviceConnection
    type: string
  - name: parameterFile
    type: string
  - name: condition
    type: string
  - name: dependsOn
    type: object
    default: []

stages:
  - stage: ${{ parameters.stageName }}
    displayName: Deploy ${{ parameters.environment }}
    dependsOn: ${{ parameters.dependsOn }}
    # Prevent this stage from running in parallel with the same deploy stage in other
    # ongoing runs of this pipeline. Instead, multiple executions of this stage will
    # be queued and run sequentially in the order that their pipelines were triggered.
    lockBehavior: sequential
    condition: ${{ parameters.condition }}
    variables:
      - group: Public API Infrastructure - ${{ parameters.environment }}
      - group: Public API Infrastructure - ${{ parameters.environment }} secrets
      - name: dataProcessorFunctionAppName
        value: $(subscription)-ees-papi-fa-processor
      - name: docsAppName
        value: $(subscription)-ees-papi-stapp-docs
      - name: bicepDeployName
        value: PublicApiInfrastructure$(upstreamPipelineBuildNumber)
    jobs:
      - template: ../jobs/deploy-infrastructure.yml
        parameters:
          serviceConnection: ${{ parameters.serviceConnection }}
          environment: ${{ parameters.environment }}
          parameterFile: ${{ parameters.parameterFile }}

      - template: ../jobs/deploy-api-docs.yml
        parameters:
          serviceConnection: ${{ parameters.serviceConnection }}
          environment: ${{ parameters.environment }}
          dependsOn: DeployPublicApiInfrastructure

      - template: ../jobs/deploy-data-processor.yml
        parameters:
          serviceConnection: ${{ parameters.serviceConnection }}
          environment: ${{ parameters.environment }}
          dependsOn: DeployPublicApiInfrastructure
