parameters:
  - name: stageName
    type: string
  - name: environment
    type: string
  - name: serviceConnection
    type: string
  - name: parameterFile
    type: string
  - name: condition
    type: string

stages:
  - stage: ${{ parameters.stageName }}
    displayName: Validate ${{ parameters.environment }}
    # Prevent this stage from running in parallel with the same deploy stage in other
    # ongoing runs of this pipeline. Instead, multiple executions of this stage will
    # be queued and run sequentially in the order that their pipelines were triggered.
    lockBehavior: sequential
    condition: ${{ parameters.condition }}
    variables:
      - group: Public API Infrastructure - ${{ parameters.environment }}
      - group: Public API Infrastructure - ${{ parameters.environment }} secrets
    jobs:
      - job: ValidateInfrastructure
        displayName: Validate infrastructure
        steps:
          - checkout: self

          - task: AzureCLI@2
            displayName: Install Bicep
            inputs:
              azureSubscription: ${{parameters.serviceConnection}}
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: az bicep install

          - template: deploy-bicep.yml
            parameters:
              displayName: Validate Bicep template
              action: validate
              serviceConnection: ${{parameters.serviceConnection}}
              parameterFile: ${{parameters.parameterFile}}
              deployContainerApp: $(deployContainerApp)
              updatePsqlFlexibleServer: $(updatePsqlFlexibleServer)
              dataProcessorFunctionAppExists: $(dataProcessorExists)
