parameters:
  - name: serviceConnection
    type: string
  - name: environment
    type: string
  - name: bicepParamFile
    type: string

jobs:
  - deployment: DeployDataFactoryPipelines
    displayName: Deploy Data Factory pipelines
    environment: ${{ parameters.environment }}
    variables:
      - name: templateDirectory
        value: $(Build.SourcesDirectory)/infrastructure/templates/data-factory-pipelines
      - name: templateFile
        value: $(templateDirectory)/main.bicep
      - name: paramDirectory
        value: $(templateDirectory)/parameters
      - name: paramFile
        value: $(paramDirectory)/main-${{ parameters.bicepParamFile }}.bicepparam
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self

            - template: ../../../../common/ci/tasks/update-azure-cli-and-extensions.yml

            - template: ../tasks/deploy-bicep.yml
              parameters:
                displayName: Validate Bicep template
                action: validate
                serviceConnection: ${{ parameters.serviceConnection }}
                parameterFile: $(paramFile)

            # Note that we need to stop pipeline triggers if making updates
            # to trigger configuration.  We restart them after deploy.
            - template: ../tasks/pipeline-triggers.yml
              parameters:
                action: stop
                serviceConnection: ${{ parameters.serviceConnection }}
                dataFactoryName: $(dataFactoryName)

            - template: ../tasks/deploy-bicep.yml
              parameters:
                displayName: Deploy Bicep template
                action: create
                serviceConnection: ${{ parameters.serviceConnection }}
                parameterFile: $(paramFile)

            - template: ../tasks/pipeline-triggers.yml
              parameters:
                action: start
                condition: succeededOrFailed()
                serviceConnection: ${{ parameters.serviceConnection }}
                dataFactoryName: '$(dataFactoryName)'
