source 'https://rubygems.org'

ruby '>= 3.2'

# For faster file watcher updates on Windows:
gem 'wdm', '~> 0.2.0', platforms: [:mswin, :mingw]

# Windows does not come with time zone data
gem 'tzinfo-data', platforms: [:mswin, :mingw, :jruby]

gem 'govuk_tech_docs'

gem 'middleman-gh-pages'

# Include linter to check for dead internal links
gem 'html-proofer'

gem 'chronic'

gem 'http'

gem 'rake'

gem "dotenv", groups: [:development, :test]
