source 'https://rubygems.org'

ruby '>= 4.0'

# Standard library gems that must be declared explicitly in Ruby 4
gem 'cgi'
gem 'ostruct'
gem 'rdoc'

# For faster file watcher updates on Windows:
gem 'wdm', '~> 0.2.0', platforms: [:windows]

# Windows does not come with time zone data
gem 'tzinfo-data', platforms: [:windows, :jruby]

gem 'govuk_tech_docs'

gem 'middleman-gh-pages'

# Include linter to check for dead internal links
gem 'html-proofer'

gem 'chronic'

gem 'http'

gem 'rake'

gem "dotenv", groups: [:development, :test]
