*** Variables ***
${ROLE_PERMISSIONS_THEME_TITLE}                         Seed theme - role permissions
${PUBLICATION_TITLE_PREFIX}                             Seed publication -${SPACE}
${PUBLICATION_SLUG_PREFIX}                              seed-publication-
${ROLE_PERMISSIONS_PUBLICATION_OWNER_PUBLICATION}       ${PUBLICATION_TITLE_PREFIX}Publication Owner
${ROLE_PERMISSIONS_PUBLICATION_APPROVER_PUBLICATION}    ${PUBLICATION_TITLE_PREFIX}Publication Release Approver
${ROLE_PERMISSIONS_RELEASE_CONTRIBUTOR_PUBLICATION}     ${PUBLICATION_TITLE_PREFIX}Release Contributor
${ROLE_PERMISSIONS_RELEASE_APPROVER_PUBLICATION}        ${PUBLICATION_TITLE_PREFIX}Release Approver
${ROLE_PERMISSIONS_DRAFT_RELEASE_TYPE}                  Academic year 2022/23
${ROLE_PERMISSIONS_HIGHER_REVIEW_RELEASE_TYPE}          Academic year 2023/24
${ROLE_PERMISSIONS_APPROVED_RELEASE_TYPE}               Academic year 2024/25
${ROLE_PERMISSIONS_PUBLISHED_RELEASE_TYPE}              Academic year 2025/26
