parameters:
  - name: serviceConnection
    type: string
  - name: environment
    type: string
  - name: displayName
    type: string
  - name: downloadPipeline
    type: string
  - name: deploymentName
    type: string
  - name: functionAppName
    type: string
  - name: artifactName
    type: string
  - name: artifactZipName
    type: string
  - name: healthCheckUrl
    type: string
  - name: dependsOn
    type: object
    default: []

jobs:
  - deployment: ${{ parameters.deploymentName }}
    displayName: ${{ parameters.displayName }}
    dependsOn: ${{ parameters.dependsOn }}
    environment: ${{ parameters.environment }}
    pool:
      vmImage: $(vmImageName)

    strategy:
      runOnce:
        deploy:
          steps:
            - download: ${{ parameters.downloadPipeline }}
              displayName: Download ${{ parameters.functionAppName }} Function App artifact
              artifact: ${{ parameters.artifactName }}
              patterns: |
                ${{ parameters.artifactZipName }}

            - template: bicep-output-variables.yml
              parameters:
                serviceConnection: ${{ parameters.serviceConnection }}

            # TODO EES-7734 - bring application-specific appsettings under the control of this
            # pipeline rather than the infrastructure pipeline, for consistency. 

            - task: AzureCLI@2
              displayName: 'Deploy ${{ parameters.functionAppName }} Function App'
              retryCountOnTaskFailure: 1
              inputs:
                azureSubscription: ${{ parameters.serviceConnection }}
                scriptType: 'bash'
                scriptLocation: 'inlineScript'
                inlineScript: |
                  set -e
                  echo "Deploying ${{ parameters.functionAppName }} Function App using zip deploy"
                  az functionapp deployment source config-zip \
                    --resource-group $(resourceGroupName) \
                    --name ${{ parameters.functionAppName }} \
                    --src '$(Pipeline.Workspace)/${{ parameters.downloadPipeline }}/${{ parameters.artifactName }}/${{ parameters.artifactZipName }}'

                  # TODO EES-7734 - provide deployedAt health check enhancement to this
                  # app deploy to ensure we're receiving successful health checks from
                  # correct version of this app.  In the meantime, sleep to give the
                  # restart a chance to begin.
                  sleep 30  

            - template: ../../../templates/public-api/ci/tasks/wait-for-endpoint-result.yml
              parameters:
                serviceConnection: ${{ parameters.serviceConnection }}
                displayName: Check ${{ parameters.functionAppName }} Function App health
                endpoint: ${{ parameters.healthCheckUrl }}
