#
# Gets the value of a secret from Key Vault. To be used only for non-sensitive secrets.
#
parameters:
  - name: serviceConnection
    type: string
  - name: keyVaultName
    type: string
  - name: secretName
    type: string
  - name: variableName
    type: string

steps:
  - task: AzureCLI@2
    displayName: Look up secret ${{ parameters.secretName }}
    inputs:
      azureSubscription: ${{ parameters.serviceConnection }}
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        set -e

        secretValue=$(az keyvault secret show \
          --vault-name ${{ parameters.keyVaultName }} \
          --name ${{ parameters.secretName }} \
          --query value -o tsv)

        echo "##vso[task.setvariable variable={{ parameters.variableName }};issecret=true]$secretValue"