# Note that previously, we were using the simpler "az upgrade --yes" script,
# but that has been broken on the runners for some time now. The below script
# provides the same upgrade in a way that works, but is quite time-consuming.

steps:
- task: Bash@3
  displayName: Upgrade Azure CLI and extensions
  inputs:
    targetType: inline
    script: |
      set -e
      sudo apt-get update && \
        sudo apt-get install --only-upgrade -y azure-cli
      
      # Grab the list of installed Azure CLI extensions and
      # for each, call "az extension update" on it.
      az extension list --query '[].name' --output tsv \
        | xargs -i az extension update --name {}
