parameters:
  - name: serviceConnection
    type: string
  - name: environment
    type: string
  - name: dependsOn
    type: object
    default: []

jobs:
  - deployment: DeployPublicApiDocs
    displayName: Deploy Public API docs
    condition: and(succeeded(), eq(variables.deployDocsSite, true))
    dependsOn: ${{ parameters.dependsOn }}
    environment: ${{ parameters.environment }}
    strategy:
      runOnce:
        deploy:
          steps:
            # Workaround for deprecation warning preventing deployment token for
            # API docs from being fetched: https://github.com/Azure/azure-cli/issues/30048
            - task: Bash@3
              name: InstallAzureCLI
              displayName: Install Azure CLI 2.64.0 as workaround
              inputs:
                targetType: inline
                script: |
                  set -e
                  pip install --force-reinstall azure-cli==2.64.0

            - task: AzureCLI@2
              displayName: Get deployment token
              inputs:
                azureSubscription: ${{ parameters.serviceConnection }}
                scriptType: bash
                scriptLocation: inlineScript
                inlineScript: |
                  set -e
                  deploymentToken=`az staticwebapp secrets list -n $(docsAppName) --query "properties.apiKey" -o tsv`
                  echo "##vso[task.setvariable variable=docsDeploymentToken;]$deploymentToken"

            - download: MainBuild
              displayName: Download Public API docs artifact
              artifact: public-api-docs

            - task: AzureStaticWebApp@0
              displayName: Deploy API docs
              inputs:
                app_location: /
                output_location: '' # Leave this empty
                skip_app_build: true
                skip_api_build: true
                azure_static_web_apps_api_token: $(docsDeploymentToken)
                cwd: $(Pipeline.Workspace)/MainBuild/public-api-docs

