parameters:
  - name: serviceConnection
    type: string

steps:
  - task: AzureCLI@2
    displayName: Convert Bicep outputs to Azure Pipeline variables
    inputs:
      azureSubscription: ${{parameters.serviceConnection}}
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        deploymentOutputs=$(az deployment group show \
        --resource-group $(resourceGroupName) \
        --name 'PublicApiInfrastructure$(upstreamPipelineBuildNumber)' \
        --query properties.outputs | jq -c 'to_entries[] | [.key, .value.value]')
        
        echo "$deploymentOutputs" | while IFS=$'\n' read -r c; do
          outputname=$(echo "$c" | jq -r '.[0]')
          outputvalue=$(echo "$c" | jq -r '.[1]')
          echo "##vso[task.setvariable variable=$outputname;]$outputvalue"
        done
