parameters:
  - name: action
    type: string
    default: create
    values:
      - create
      - validate
  - name: displayName
    type: string
  - name: serviceConnection
    type: string
  - name: parameterFile
    type: string
  - name: deployContainerApp
    type: string
  - name: updatePsqlFlexibleServer
    type: string
  - name: deployAlerts
    type: string
  - name: dataProcessorExists
    type: string

steps:
  - task: AzureCLI@2
    displayName: ${{ parameters.displayName }}
    inputs:
      azureSubscription: ${{ parameters.serviceConnection }}
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        set -e
        
        az deployment group ${{ parameters.action }} \
          --name $(infraDeployName) \
          --resource-group $(resourceGroupName) \
          --template-file $(templateFile) \
          --parameters ${{ parameters.parameterFile }} \
          --parameters \
              subscription='$(subscription)' \
              resourceTags='$(resourceTags)' \
              postgreSqlAdminName='$(postgreSqlAdminName)' \
              postgreSqlAdminPassword='$(postgreSqlAdminPassword)' \
              postgreSqlFirewallRules='$(maintenanceFirewallRules)' \
              postgreSqlEntraIdAdminPrincipals='$(postgreSqlEntraIdAdminPrincipals)' \
              storageFirewallRules='$(maintenanceFirewallRules)' \
              acrResourceGroupName='$(acrResourceGroupName)' \
              dockerImagesTag='$(resources.pipeline.MainBuild.runName)' \
              deployContainerApp=${{ parameters.deployContainerApp }} \
              updatePsqlFlexibleServer=${{ parameters.updatePsqlFlexibleServer }} \
              deployAlerts=${{ parameters.deployAlerts }} \
              dataProcessorFunctionAppExists=${{ parameters.dataProcessorExists }} \
              dataProcessorAppRegistrationClientId='$(dataProcessorAppRegistrationClientId)' \
              apiAppRegistrationClientId='$(apiAppRegistrationClientId)'
