FROM quay.io/keycloak/keycloak:21.1.2
EXPOSE 8080

ENV KEYCLOAK_USER=admin
ENV KEYCLOAK_PASSWORD=admin
ENV KEYCLOAK_IMPORT=/tmp/keycloak-ees-realm.json 

COPY ./keycloak-ees-realm.json /tmp/keycloak-ees-realm.json