parameters:
  - name: serviceConnection
    type: string
  - name: environment
    type: string
  - name: bicepParamFile
    type: string

jobs:
  - deployment: DeployCoreInfrastructure
    displayName: Deploy Core infrastructure
    environment: ${{ parameters.environment }}
    variables:
      templateDirectory: $(Build.SourcesDirectory)/infrastructure/templates/core
      templateFile: $(templateDirectory)/main.bicep
      paramDirectory: $(templateDirectory)/parameters
      paramFile: $(paramDirectory)/main-${{ parameters.bicepParamFile }}.bicepparam
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self

            - template: ../../../../common/ci/tasks/update-azure-cli-and-extensions.yml

            - template: ../tasks/deploy-bicep.yml
              parameters:
                displayName: Validate Bicep template
                action: validate
                serviceConnection: ${{ parameters.serviceConnection }}
                parameterFile: $(paramFile)
                deploySubnets: false
                deployPrivateDnsZones: false
                deployAzureFrontDoor: false
                deployApplicationGateway: false
                deployDataFactory: false
                deployContainerRegistry: false
                deployRecoveryServicesVault: false
                deployAlerts: false

            - template: ../tasks/deploy-bicep.yml
              parameters:
                displayName: Deploy Bicep template
                action: create
                serviceConnection: ${{ parameters.serviceConnection }}
                parameterFile: $(paramFile)
                deploySubnets: $(deploySubnets)
                deployPrivateDnsZones: $(deployPrivateDnsZones)
                deployAzureFrontDoor: $(deployAzureFrontDoor)
                deployApplicationGateway: $(deployApplicationGateway)
                deployDataFactory: $(deployDataFactory)
                deployContainerRegistry: $(deployContainerRegistry)
                deployRecoveryServicesVault: $(deployRecoveryServicesVault)
                deployAlerts: $(deployAlerts)
