CREATE TYPE IdListIntegerType AS TABLE
(
    id INT
);

CREATE TYPE IdListVarcharType AS TABLE
(
    id VARCHAR(max)
);

CREATE TYPE TimePeriodListType AS TABLE
(
    year INT,
    timeIdentifier VARCHAR(6)
);

CREATE TYPE IdListGuidType AS TABLE
(
    id UNIQUEIDENTIFIER
);

CREATE TYPE ThemeType AS TABLE(
  Id UNIQUEIDENTIFIER NOT NULL,
  Title VARCHAR (MAX) NOT NULL,
  Slug VARCHAR(MAX) NOT NULL
);

CREATE TYPE dbo.TopicType AS TABLE(
  Id UNIQUEIDENTIFIER NOT NULL,
  Title VARCHAR(MAX) NOT NULL,
  Slug VARCHAR(MAX) NOT NULL,
  ThemeId UNIQUEIDENTIFIER NOT NULL
);

CREATE TYPE dbo.PublicationType AS TABLE(
  Id UNIQUEIDENTIFIER NOT NULL,
  Title VARCHAR(MAX) NOT NULL,
  Slug VARCHAR(MAX) NOT NULL,
  TopicId UNIQUEIDENTIFIER NOT NULL
);

CREATE TYPE dbo.FilterType AS TABLE(
    Id UNIQUEIDENTIFIER NOT NULL,
    Hint VARCHAR(MAX) NOT NULL,
    Label VARCHAR(MAX) NOT NULL,
    Name VARCHAR(MAX) NOT NULL,
    SubjectId UNIQUEIDENTIFIER NOT NULL
);

CREATE TYPE dbo.FilterFootnoteType AS TABLE(
   FilterId UNIQUEIDENTIFIER NOT NULL,
   FootnoteId UNIQUEIDENTIFIER NOT NULL
);

CREATE TYPE dbo.FilterGroupType AS TABLE(
   Id UNIQUEIDENTIFIER NOT NULL,
   FilterId UNIQUEIDENTIFIER NOT NULL,
   Label VARCHAR(MAX) NOT NULL
);

CREATE TYPE dbo.FilterGroupFootnoteType AS TABLE(
    FilterGroupId UNIQUEIDENTIFIER NOT NULL,
    FootnoteId UNIQUEIDENTIFIER NOT NULL
);

CREATE TYPE dbo.FilterItemType AS TABLE(
    Id UNIQUEIDENTIFIER NOT NULL,
    Label VARCHAR(MAX) NOT NULL,
    FilterGroupId UNIQUEIDENTIFIER NOT NULL
);

CREATE TYPE dbo.FilterItemFootnoteType AS TABLE(
   FilterItemId UNIQUEIDENTIFIER NOT NULL,
   FootnoteId UNIQUEIDENTIFIER NOT NULL
);

CREATE TYPE dbo.FootnoteType AS TABLE(
   Id UNIQUEIDENTIFIER NOT NULL,
   Content VARCHAR(MAX) NOT NULL,
);

CREATE TYPE dbo.IndicatorType AS TABLE(
   Id UNIQUEIDENTIFIER NOT NULL,
   Label VARCHAR(MAX) NOT NULL,
   Name VARCHAR(MAX) NOT NULL,
   Unit VARCHAR(MAX) NOT NULL,
   IndicatorGroupId UNIQUEIDENTIFIER NOT NULL
);

CREATE TYPE dbo.IndicatorFootnoteType AS TABLE(
  IndicatorId UNIQUEIDENTIFIER NOT NULL,
  FootnoteId UNIQUEIDENTIFIER NOT NULL
);

CREATE TYPE dbo.IndicatorGroupType AS TABLE(
    Id UNIQUEIDENTIFIER NOT NULL,
    Label VARCHAR(MAX) NOT NULL,
    SubjectId UNIQUEIDENTIFIER NOT NULL
);

CREATE TYPE dbo.LocationType AS TABLE(
   Id UNIQUEIDENTIFIER NOT NULL,
XXX
);

CREATE TYPE dbo.SubjectType AS TABLE(
   Id UNIQUEIDENTIFIER NOT NULL,
   Name VARCHAR(MAX) NOT NULL,
   ReleaseId UNIQUEIDENTIFIER NOT NULL
);

CREATE TYPE dbo.SubjectFootnoteType AS TABLE(
  SubjectId UNIQUEIDENTIFIER NOT NULL,
  FootnoteId UNIQUEIDENTIFIER NOT NULL
);


