create type LocationType as table
(
    Id                              uniqueidentifier not null,
    GeographicLevel                 nvarchar(6),
    Country_Code                    nvarchar(450),
    Country_Name                    nvarchar(max),
    EnglishDevolvedArea_Code        nvarchar(450),
    EnglishDevolvedArea_Name        nvarchar(max),
    Institution_Code                nvarchar(450),
    Institution_Name                nvarchar(max),
    LocalAuthority_Code             nvarchar(450),
    LocalAuthority_OldCode          nvarchar(450),
    LocalAuthority_Name             nvarchar(max),
    LocalAuthorityDistrict_Code     nvarchar(450),
    LocalAuthorityDistrict_Name     nvarchar(max),
    LocalEnterprisePartnership_Code nvarchar(450),
    LocalEnterprisePartnership_Name nvarchar(max),
    MayoralCombinedAuthority_Code   nvarchar(450),
    MayoralCombinedAuthority_Name   nvarchar(max),
    MultiAcademyTrust_Code          nvarchar(450),
    MultiAcademyTrust_Name          nvarchar(max),
    OpportunityArea_Code            nvarchar(450),
    OpportunityArea_Name            nvarchar(max),
    ParliamentaryConstituency_Code  nvarchar(450),
    ParliamentaryConstituency_Name  nvarchar(max),
    PlanningArea_Code               nvarchar(450),
    PlanningArea_Name               nvarchar(max),
    Provider_Code                   nvarchar(450),
    Provider_Name                   nvarchar(max),
    Region_Code                     nvarchar(450),
    Region_Name                     nvarchar(max),
    RscRegion_Code                  nvarchar(450),
    School_Code                     nvarchar(450),
    School_Name                     nvarchar(max),
    Sponsor_Code                    nvarchar(450),
    Sponsor_Name                    nvarchar(max),
    Ward_Code                       nvarchar(450),
    Ward_Name                       nvarchar(max)
);
