REVOKE ALL ON [dbo].[BoundaryLevel] TO [importer];
REVOKE ALL ON [dbo].[Filter] TO [importer];
REVOKE ALL ON [dbo].[FilterFootnote] TO [importer];
REVOKE ALL ON [dbo].[FilterGroup] TO [importer];
REVOKE ALL ON [dbo].[FilterGroupFootnote] TO [importer];
REVOKE ALL ON [dbo].[FilterItem] TO [importer];
REVOKE ALL ON [dbo].[FilterItemFootnote] TO [importer];
REVOKE ALL ON [dbo].[Footnote] TO [importer];
REVOKE ALL ON [dbo].[Indicator] TO [importer];
REVOKE ALL ON [dbo].[IndicatorFootnote] TO [importer];
REVOKE ALL ON [dbo].[IndicatorGroup] TO [importer];
REVOKE ALL ON [dbo].[Location] TO [importer];
REVOKE ALL ON [dbo].[Observation] TO [importer];
REVOKE ALL ON [dbo].[ObservationFilterItem] TO [importer];
REVOKE ALL ON [dbo].[ReleaseFootnote] TO [importer];
REVOKE ALL ON [dbo].[ReleaseSubject] TO [importer];
REVOKE ALL ON [dbo].[ReleaseVersion] TO [importer];
REVOKE ALL ON [dbo].[Subject] TO [importer];
REVOKE ALL ON [dbo].[SubjectFootnote] TO [importer];

GRANT SELECT, INSERT, UPDATE ON [dbo].[Filter] TO [importer];
GRANT SELECT, INSERT ON [dbo].[FilterItem] TO [importer];
GRANT SELECT, INSERT ON [dbo].[FilterGroup] TO [importer];
GRANT SELECT, INSERT ON [dbo].[Indicator] TO [importer];
GRANT SELECT, INSERT ON [dbo].[IndicatorGroup] TO [importer];
GRANT SELECT, INSERT ON [dbo].[Location] TO [importer];
GRANT SELECT, INSERT ON [dbo].[Observation] TO [importer];
GRANT SELECT, INSERT ON [dbo].[ObservationFilterItem] TO [importer];
GRANT SELECT ON [dbo].[Subject] TO [importer];