trigger:
  paths:
    include:
    - infrastructure/

pr:
  paths:
    include:
    - infrastructure/

pool:
  vmImage: 'windows-latest'

steps:
- task: AzSKARMTemplateChecker@4
  inputs:
    ARMTemplateFilePath: '$(System.DefaultWorkingDirectory)/infrastructure/templates/'
    ARMTemplateParameterFilePath: '$(System.DefaultWorkingDirectory)/infrastructure/parameters/'
    SkipControlsFromFile: '$(System.DefaultWorkingDirectory)/infrastructure/template-checker/skip-controls.csv'