trigger:
  batch: true
  branches:
    include:
    - master
    - dev
  paths:
    include:
    - infrastructure/*
    exclude:
    - README.md
pr: none

pool:
  vmImage: 'windows-latest'

steps:
- task: AzSKARMTemplateChecker@4
  enabled: false
  inputs:
    ARMTemplateFilePath: '$(System.DefaultWorkingDirectory)/infrastructure/templates/'
    ARMTemplateParameterFilePath: '$(System.DefaultWorkingDirectory)/infrastructure/parameters/'
    SkipControlsFromFile: '$(System.DefaultWorkingDirectory)/infrastructure/template-checker/skip-controls.csv'
- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'arm-template'
    targetPath: 'infrastructure'