trigger:
  batch: true
  branches:
    include:
    - master
    - dev
    - test
  paths:
    include:
    - infrastructure/*
    exclude:
    - README.md
    - infrastructure/templates/public-api/*
    - infrastructure/templates/search/*
pr: none

pool:
  vmImage: windows-latest

steps:
- task: PublishPipelineArtifact@0
  inputs:
    artifactName: arm-template
    targetPath: infrastructure
