parameters:
  - name: serviceConnection
    type: string
  - name: environment
    type: string
  - name: dependsOn
    type: object
    default: []

jobs:
  - deployment: DeployScreenerFunction
    displayName: Deploy Screener Function
    dependsOn: ${{ parameters.dependsOn }}
    environment: ${{ parameters.environment }}
    pool:
      vmImage: $(vmImageName)

    strategy:
      runOnce:
        deploy:
          steps:
          - template: ../../../../common/ci/tasks/bicep-output-variables.yml
            parameters:
              serviceConnection: ${{ parameters.serviceConnection }}

          - task: AzureCLI@2
            displayName: Look up Screener app registration client id from Key Vault
            inputs:
              azureSubscription: ${{ parameters.serviceConnection }}
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                set -e

                clientId=$(az keyvault secret show \
                  --vault-name $(keyVaultName) \
                  --name ees-screener-app-registration-client-id \
                  --query value -o tsv)

                echo "##vso[task.setvariable variable=screenerAppRegistrationClientId]$clientId"

          - template: ../../../public-api/ci/tasks/wait-for-endpoint-success.yml
            parameters:
              serviceConnection: ${{ parameters.serviceConnection }}
              displayName: Check the Screener API Function App is healthy after deployment
              endpoint: '$(screenerFunctionAppUrl)/api/healthcheck'
              accessTokenScope: $(screenerAppRegistrationClientId)
              maxAttempts: 50
