#nullable enable
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace GovUk.Education.ExploreEducationStatistics.Common.ViewModels;

/// <summary>
/// Describes a problem that occurred whilst processing the request.
/// The format is based on RFC7807.
/// </summary>
public record ProblemDetailsViewModel
{
    /// <summary>
    /// A URI reference (RFC3986) that identifies the problem type. It should
    /// provide human-readable documentation for the problem type.
    /// </summary>
    /// <example>https://tools.ietf.org/html/rfc9110#section-15.5.1</example>
    [JsonPropertyOrder(-5)]
    [JsonProperty(Order = -5)]
    [Required]
    public string? Type { get; set; }

    /// <summary>
    /// A short, human-readable summary of the problem type.
    /// </summary>
    /// <example>One or more validation errors occurred.</example>
    [JsonPropertyOrder(-4)]
    [JsonProperty(Order = -4)]
    [Required]
    public string? Title { get; set; }

    /// <summary>
    /// The HTTP status code generated by the origin server for the problem.
    /// </summary>
    /// <example>400</example>
    [JsonPropertyOrder(-3)]
    [JsonProperty(Order = -3)]
    [Required]
    public virtual int Status { get; set; } = StatusCodes.Status500InternalServerError;

    /// <summary>
    /// A human-readable explanation specific to the problem.
    /// </summary>
    /// <example>More detail about the problem.</example>
    [JsonPropertyOrder(-2)]
    [JsonProperty(Order = -2)]
    public string? Detail { get; set; }

    /// <summary>
    /// A URI reference that identifies the specific occurrence of the problem.
    /// It may or may not yield further information about the problem.
    /// </summary>
    /// <example>https://example.com</example>
    [JsonPropertyOrder(-1)]
    [JsonProperty(Order = -1)]
    public string? Instance { get; set; }

    [System.Text.Json.Serialization.JsonExtensionData]
    [Newtonsoft.Json.JsonExtensionData]
    public IDictionary<string, object?> Extensions { get; set; }
        = new Dictionary<string, object?>(StringComparer.Ordinal);

    public static ProblemDetailsViewModel Create(ProblemDetails problemDetails)
    {
        return new ProblemDetailsViewModel
        {
            Type = problemDetails.Type,
            Title = problemDetails.Title,
            Status = problemDetails.Status ?? StatusCodes.Status500InternalServerError,
            Detail = problemDetails.Detail,
            Instance = problemDetails.Instance,
            Extensions = problemDetails.Extensions
        };
    }
}
