parameters:
  - name: serviceConnection
    type: string
  - name: environment
    type: string
  - name: dependsOn
    type: object
    default: []

jobs:
  - deployment: DeploySearchDocsFunction
    displayName: Deploy Search Docs Function
    dependsOn: ${{ parameters.dependsOn }}
    environment: ${{ parameters.environment }}
    pool:
      vmImage: $(vmImageName)

    strategy:
      runOnce:
        deploy:
          steps:
            - download: MainBuild
              displayName: Download Search Docs Function App artifact
              artifact: search-function-app

            - template: ../../../public-api/ci/tasks/bicep-output-variables.yml
              parameters:
                serviceConnection: ${{ parameters.serviceConnection }}

            - task: AzureCLI@2
              displayName: 'Deploy Search Docs Function App using az cli'
              retryCountOnTaskFailure: 1
              inputs:
                azureSubscription: ${{ parameters.serviceConnection }}
                scriptType: 'bash'
                scriptLocation: 'inlineScript'
                inlineScript: |
                  set -e
                  echo "Deploying Search Docs Function App using zip deploy"
                  az functionapp deployment source config-zip \
                    --resource-group $(resourceGroupName) \
                    --name $(searchDocsFunctionAppName) \
                    --src '$(Pipeline.Workspace)/MainBuild/search-function-app/GovUk.Education.ExploreEducationStatistics.Content.Search.FunctionApp.zip'

            - template: ../../../public-api/ci/tasks/wait-for-endpoint-success.yml
              parameters:
                serviceConnection: ${{ parameters.serviceConnection }}
                displayName: Check the Search Docs Function App is healthy after deployment
                endpoint: $(searchDocsFunctionAppUrl)/api/HealthCheck

