parameters:
  - name: serviceConnection
    type: string
  - name: environment
    type: string
  - name: bicepParamFile
    type: string

jobs:
  - deployment: DeploySearchInfrastructure
    displayName: Deploy Search Infrastructure
    environment: ${{ parameters.environment }}
    variables:
      - group: Common - ${{ parameters.environment }}
      - name: templateDirectory
        value: $(Build.SourcesDirectory)/infrastructure/templates/search
      - name: templateFile
        value: $(templateDirectory)/main.bicep
      - name: paramDirectory
        value: $(templateDirectory)/parameters
      - name: paramFile
        value: $(paramDirectory)/main-${{ parameters.bicepParamFile }}.bicepparam
      - name: searchServiceSearchIndexName
        value: 'index-1'
      - name: searchServiceSearchIndexerName
        value: ${{ variables.searchServiceSearchIndexName }}-indexer
      - name: searchServiceSearchIndexerParsingMode
        value: 'default'
      - name: searchServiceNLSearchIndexName
        value: 'nl-search-index'
      - name: searchServiceNLSearchIndexerName
        value: ${{ variables.searchServiceNLSearchIndexName }}-indexer
      - name: searchServiceNLSearchIndexerParsingMode
        value: 'json'
      - name: searchServiceNLDatasetSearchIndexName
        value: 'nl-dataset-search-index'
      - name: searchServiceNLDatasetSearchIndexerName
        value: ${{ variables.searchServiceNLDatasetSearchIndexName }}-indexer
      - name: searchServiceNLDatasetSearchIndexerParsingMode
        value: 'json'
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self
            - download: none

            - template: ../../../../common/ci/tasks/update-azure-cli-and-extensions.yml

            - template: ../tasks/deploy-bicep.yml
              parameters:
                displayName: Validate Bicep template
                action: validate
                serviceConnection: ${{ parameters.serviceConnection }}
                parameterFile: $(paramFile)
                searchServiceIndexerName: ${{ variables.searchServiceSearchIndexerName }}
                searchDocsFunctionAppExists: false

            - template: ../../../../common/ci/tasks/check-function-app-exists.yml
              parameters:
                serviceConnection: ${{ parameters.serviceConnection }}
                resourceGroupName: $(resourceGroupName)
                functionAppName: $(searchDocsFunctionAppName)
                variableName: searchDocsFunctionAppExists

            - template: ../tasks/deploy-bicep.yml
              parameters:
                displayName: Deploy Bicep template
                action: create
                serviceConnection: ${{ parameters.serviceConnection }}
                parameterFile: $(paramFile)
                searchServiceIndexerName: ${{ variables.searchServiceSearchIndexerName }}
                searchDocsFunctionAppExists: $(searchDocsFunctionAppExists)

            - template: ../../../../common/ci/tasks/bicep-output-variables.yml
              parameters:
                serviceConnection: ${{ parameters.serviceConnection }}

            # Deploy Azure AI Search index/indexer/data source configuration for search documents
            - template: ../tasks/deploy-search-service-config.yml
              parameters:
                serviceConnection: ${{ parameters.serviceConnection }}
                indexCorsAllowedOrigins:
                  - $(publicSiteUrl)
                  - 'http://localhost:3000'
                dataSourceConnectionString: $(searchStorageAccountManagedIdentityConnectionString)
                dataSourceContainerName: $(searchDocumentsContainerName)
                indexName: ${{ variables.searchServiceSearchIndexName }}
                indexerName: ${{ variables.searchServiceSearchIndexerName }}
                indexerOutputFieldMappingsFilePath: $(templateDirectory)/application/indexer-output-field-mappings/index-1.json
                indexerParsingMode: ${{ variables.searchServiceSearchIndexerParsingMode }}
                searchServiceEndpoint: $(searchServiceEndpoint)

            # Deploy Azure AI Search index/indexer/data source configuration for natural language search documents
            - template: ../tasks/deploy-search-service-config.yml
              parameters:
                serviceConnection: ${{ parameters.serviceConnection }}
                indexCorsAllowedOrigins:
                  - $(publicSiteUrl)
                  - 'http://localhost:3000'
                dataSourceConnectionString: $(searchStorageAccountManagedIdentityConnectionString)
                dataSourceContainerName: $(nlSearchDocumentsContainerName)
                indexName: ${{ variables.searchServiceNLSearchIndexName }}
                indexerName: ${{ variables.searchServiceNLSearchIndexerName }}
                indexerParsingMode: ${{ variables.searchServiceNLSearchIndexerParsingMode }}
                searchServiceEndpoint: $(searchServiceEndpoint)

            # Deploy Azure AI Search index/indexer/data source configuration for natural language dataset search documents
            - template: ../tasks/deploy-search-service-config.yml
              parameters:
                serviceConnection: ${{ parameters.serviceConnection }}
                indexCorsAllowedOrigins:
                  - $(publicSiteUrl)
                  - 'http://localhost:3000'
                dataSourceConnectionString: $(searchStorageAccountManagedIdentityConnectionString)
                dataSourceContainerName: $(nlDatasetSearchDocumentsContainerName)
                indexName: ${{ variables.searchServiceNLDatasetSearchIndexName }}
                indexerName: ${{ variables.searchServiceNLDatasetSearchIndexerName }}
                indexerParsingMode: ${{ variables.searchServiceNLDatasetSearchIndexerParsingMode }}
                searchServiceEndpoint: $(searchServiceEndpoint)