parameters:
  - name: serviceConnection
    type: string
  - name: environment
    type: string
  - name: bicepParamFile
    type: string

jobs:
  - deployment: DeploySearchInfrastructure
    displayName: Deploy Search Infrastructure
    environment: ${{ parameters.environment }}
    variables:
      - group: Common - ${{ parameters.environment }}
      - name: templateDirectory
        value: $(Build.SourcesDirectory)/infrastructure/templates/search
      - name: templateFile
        value: $(templateDirectory)/main.bicep
      - name: paramDirectory
        value: $(templateDirectory)/parameters
      - name: paramFile
        value: $(paramDirectory)/main-${{ parameters.bicepParamFile }}.bicepparam
      # 'Search' variables
      - name: searchServiceSearchIndexName
        value: 'index-1'
      - name: searchServiceSearchIndexDefinitionFilePath
        value: $(templateDirectory)/application/indexes/search/${{ variables.searchServiceSearchIndexName }}.json
      - name: searchServiceSearchIndexerName
        value: ${{ variables.searchServiceSearchIndexName }}-indexer
      - name: searchServiceSearchIndexerParsingMode
        value: 'default'
      - name: searchServiceSearchIndexerOutputFieldMappingsFilePath
        value: $(templateDirectory)/application/indexer-output-field-mappings/search/${{ variables.searchServiceSearchIndexName }}.json
      # 'Natural language search dataset' variables
      - name: searchServiceNLSearchDatasetIndexName
        value: 'nl-search-dataset-index'
      - name: searchServiceNLSearchDatasetIndexDefinitionFilePath
        value: $(templateDirectory)/application/indexes/nl-search/${{ variables.searchServiceNLSearchDatasetIndexName }}.json
      - name: searchServiceNLSearchDatasetIndexerName
        value: ${{ variables.searchServiceNLSearchDatasetIndexName }}-indexer
      - name: searchServiceNLSearchDatasetIndexerParsingMode
        value: 'json'
      # 'Natural language search filter' variables
      - name: searchServiceNLSearchFilterIndexName
        value: 'nl-search-filter-index'
      - name: searchServiceNLSearchFilterIndexDefinitionFilePath
        value: $(templateDirectory)/application/indexes/nl-search/${{ variables.searchServiceNLSearchFilterIndexName }}.json
      - name: searchServiceNLSearchFilterIndexerName
        value: ${{ variables.searchServiceNLSearchFilterIndexName }}-indexer
      - name: searchServiceNLSearchFilterIndexerParsingMode
        value: 'json'
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self
            - download: none

            - template: ../../../../common/ci/tasks/update-azure-cli-and-extensions.yml

            - template: ../tasks/deploy-bicep.yml
              parameters:
                displayName: Validate Bicep template
                action: validate
                serviceConnection: ${{ parameters.serviceConnection }}
                parameterFile: $(paramFile)
                naturalLanguageSearchFunctionAppExists: false
                searchDocsFunctionAppExists: false
                searchServiceNLSearchFilterIndexName: ${{ variables.searchServiceNLSearchFilterIndexName }}
                searchServiceNLSearchDatasetIndexName: ${{ variables.searchServiceNLSearchDatasetIndexName }}
                searchServiceSearchIndexerName: ${{ variables.searchServiceSearchIndexerName }}

            - template: ../../../../common/ci/tasks/check-function-app-exists.yml
              parameters:
                serviceConnection: ${{ parameters.serviceConnection }}
                resourceGroupName: $(resourceGroupName)
                functionAppName: $(searchDocsFunctionAppName)
                variableName: searchDocsFunctionAppExists

            - template: ../../../../common/ci/tasks/check-function-app-exists.yml
              parameters:
                serviceConnection: ${{ parameters.serviceConnection }}
                resourceGroupName: $(resourceGroupName)
                functionAppName: $(naturalLanguageSearchFunctionAppName)
                variableName: naturalLanguageSearchFunctionAppExists

            - template: ../tasks/deploy-bicep.yml
              parameters:
                displayName: Deploy Bicep template
                action: create
                serviceConnection: ${{ parameters.serviceConnection }}
                parameterFile: $(paramFile)
                naturalLanguageSearchFunctionAppExists: $(naturalLanguageSearchFunctionAppExists)
                searchDocsFunctionAppExists: $(searchDocsFunctionAppExists)
                searchServiceNLSearchFilterIndexName: ${{ variables.searchServiceNLSearchFilterIndexName }}
                searchServiceNLSearchDatasetIndexName: ${{ variables.searchServiceNLSearchDatasetIndexName }}
                searchServiceSearchIndexerName: ${{ variables.searchServiceSearchIndexerName }}

            - template: ../../../../common/ci/tasks/bicep-output-variables.yml
              parameters:
                serviceConnection: ${{ parameters.serviceConnection }}

            # Deploy Azure AI Search index/indexer/data source configuration for 'Search' documents
            - template: ../tasks/deploy-search-service-config.yml
              parameters:
                serviceConnection: ${{ parameters.serviceConnection }}
                indexCorsAllowedOrigins:
                  - $(publicSiteUrl)
                  - 'http://localhost:3000'
                dataSourceConnectionString: $(searchStorageAccountManagedIdentityConnectionString)
                dataSourceContainerName: $(searchDocumentsContainerName)
                indexName: ${{ variables.searchServiceSearchIndexName }}
                indexDefinitionFilePath: ${{ variables.searchServiceSearchIndexDefinitionFilePath }}
                indexerName: ${{ variables.searchServiceSearchIndexerName }}
                indexerOutputFieldMappingsFilePath: ${{ variables.searchServiceSearchIndexerOutputFieldMappingsFilePath }}
                indexerParsingMode: ${{ variables.searchServiceSearchIndexerParsingMode }}
                searchServiceEndpoint: $(searchServiceEndpoint)

            # Deploy Azure AI Search index/indexer/data source configuration for 'Natural language search dataset' documents
            - template: ../tasks/deploy-search-service-config.yml
              parameters:
                serviceConnection: ${{ parameters.serviceConnection }}
                indexCorsAllowedOrigins:
                  - $(publicSiteUrl)
                  - 'http://localhost:3000'
                dataSourceConnectionString: $(searchStorageAccountManagedIdentityConnectionString)
                dataSourceContainerName: $(nlSearchDatasetDocumentsContainerName)
                indexName: ${{ variables.searchServiceNLSearchDatasetIndexName }}
                indexDefinitionFilePath: ${{ variables.searchServiceNLSearchDatasetIndexDefinitionFilePath }}
                indexerName: ${{ variables.searchServiceNLSearchDatasetIndexerName }}
                indexerParsingMode: ${{ variables.searchServiceNLSearchDatasetIndexerParsingMode }}
                searchServiceEndpoint: $(searchServiceEndpoint)

            # Deploy Azure AI Search index/indexer/data source configuration for 'Natural language search filter' documents
            - template: ../tasks/deploy-search-service-config.yml
              parameters:
                serviceConnection: ${{ parameters.serviceConnection }}
                indexCorsAllowedOrigins:
                  - $(publicSiteUrl)
                  - 'http://localhost:3000'
                dataSourceConnectionString: $(searchStorageAccountManagedIdentityConnectionString)
                dataSourceContainerName: $(nlSearchFilterDocumentsContainerName)
                indexName: ${{ variables.searchServiceNLSearchFilterIndexName }}
                indexDefinitionFilePath: ${{ variables.searchServiceNLSearchFilterIndexDefinitionFilePath }}
                indexerName: ${{ variables.searchServiceNLSearchFilterIndexerName }}
                indexerParsingMode: ${{ variables.searchServiceNLSearchFilterIndexerParsingMode }}
                searchServiceEndpoint: $(searchServiceEndpoint)