parameters:
  - name: serviceConnection
    type: string
  - name: environment
    type: string
  - name: bicepParamFile
    type: string

jobs:
  - deployment: DeploySearchInfrastructure
    displayName: Deploy Search Infrastructure
    environment: ${{ parameters.environment }}
    variables:
      - group: Common - ${{ parameters.environment }}
      - name: templateDirectory
        value: $(Build.SourcesDirectory)/infrastructure/templates/search
      - name: templateFile
        value: $(templateDirectory)/main.bicep
      - name: paramDirectory
        value: $(templateDirectory)/parameters
      - name: paramFile
        value: $(paramDirectory)/main-${{ parameters.bicepParamFile }}.bicepparam
      - name: searchServiceIndexName
        value: 'index-1'
      - name: searchServiceIndexerName
        value: ${{ variables.searchServiceIndexName }}-indexer
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self
            - download: none

            - script: az upgrade --yes
              displayName: Upgrade Azure CLI and extensions

            - template: ../tasks/deploy-bicep.yml
              parameters:
                displayName: Validate Bicep template
                action: validate
                serviceConnection: ${{ parameters.serviceConnection }}
                parameterFile: $(paramFile)
                searchServiceIndexerName: ${{ variables.searchServiceIndexerName }}
                searchDocsFunctionAppExists: false

            - template: ../../../public-api/ci/tasks/check-function-app-exists.yml
              parameters:
                serviceConnection: ${{ parameters.serviceConnection }}
                resourceGroupName: $(resourceGroupName)
                functionAppName: $(searchDocsFunctionAppName)
                variableName: searchDocsFunctionAppExists

            - template: ../tasks/deploy-bicep.yml
              parameters:
                displayName: Deploy Bicep template
                action: create
                serviceConnection: ${{ parameters.serviceConnection }}
                parameterFile: $(paramFile)
                searchServiceIndexerName: ${{ variables.searchServiceIndexerName }}
                searchDocsFunctionAppExists: $(searchDocsFunctionAppExists)

            - template: ../../../../common/ci/tasks/bicep-output-variables.yml
              parameters:
                serviceConnection: ${{ parameters.serviceConnection }}

            - template: ../tasks/deploy-search-service-config.yml
              parameters:
                serviceConnection: ${{ parameters.serviceConnection }}
                indexCorsAllowedOrigins:
                  - $(publicSiteUrl)
                  - 'https://localhost:3000'
                  - 'http://localhost:3000'
                dataSourceConnectionString: $(searchStorageAccountManagedIdentityConnectionString)
                dataSourceContainerName: $(searchableDocumentsContainerName)
                indexName: ${{ variables.searchServiceIndexName }}
                indexerName: ${{ variables.searchServiceIndexerName }}
                searchServiceEndpoint: $(searchServiceEndpoint)
