FROM node:10.15.3-alpine

RUN apk add --no-cache git
WORKDIR /data
RUN git clone -q --progress  https://github.com/Azure/Azurite.git
WORKDIR /data/Azurite

RUN git checkout v3.0.0-preview
RUN npm install
RUN npm run build
RUN npm install -g

ENTRYPOINT ["azurite", "--blobHost", "0.0.0.0"]

