using System;
using Microsoft.EntityFrameworkCore.Migrations;

namespace GovUk.Education.ExploreEducationStatistics.Admin.Migrations.ContentMigrations
{
    public partial class EES2878UpdateReleaseTypeTitles : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.UpdateData(
                table: "ReleaseTypes",
                keyColumn: "Id",
                keyValue: new Guid("1821abb8-68b0-431b-9770-0bea65d02ff0"),
                column: "Title",
                value: "Ad Hoc Statistics");

            // Previous migration added this Id without updating ContentDbContext
            // So autogenerated migration was InsertData - manually changed this to
            // UpdateData
            migrationBuilder.UpdateData(
                table: "ReleaseTypes",
                keyColumn: "Id",
                keyValue: new Guid("15bd4f57-c837-4821-b308-7f4169cd9330"),
                column: "Title",
                value: "Management Information");

            // Previous migration added this Id without updating ContentDbContext
            // So autogenerated migration was InsertData - manually changed this to
            // UpdateData
            migrationBuilder.UpdateData(
                table: "ReleaseTypes",
                keyColumn: "Id",
                keyValue: new Guid("f5de8522-3150-435d-98d5-1d14763f8c54"),
                column: "Title",
                value: "Experimental Statistics");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // Manually changed from DeleteData - see above comments
            migrationBuilder.UpdateData(
                table: "ReleaseTypes",
                keyColumn: "Id",
                keyValue: new Guid("f5de8522-3150-435d-98d5-1d14763f8c54"),
                column: "Title",
                value: "Experimental");

            // Manually changed from DeleteData - see above comments
            migrationBuilder.UpdateData(
                table: "ReleaseTypes",
                keyColumn: "Id",
                keyValue: new Guid("15bd4f57-c837-4821-b308-7f4169cd9330"),
                column: "Title",
                value: "Transparency Data");

            migrationBuilder.UpdateData(
                table: "ReleaseTypes",
                keyColumn: "Id",
                keyValue: new Guid("1821abb8-68b0-431b-9770-0bea65d02ff0"),
                column: "Title",
                value: "Ad Hoc");
        }
    }
}
