-- Create initial glossary entries

DECLARE @bau1UserId uniqueidentifier = (SELECT Id FROM Users WHERE Email = 'ees-bau1@education.gov.uk');

INSERT INTO dbo.GlossaryEntries
(Id, Created, CreatedById, Title, Slug, Body)
VALUES
-- A
(NEWID(), GETUTCDATE(), @bau1UserId, 'Absence', 'absence', N'<p>When a pupil misses (or is absent from) at least 1 possible school session.</p><p>Counted in sessions, where 1 session is equivalent to half-a-day.</p><p>There are 4 types of absence:</p><ul><li><a href="/glossary#authorised-absence">authorised absence</a></li><li><a href="/glossary#overall-absence">overall absence</a></li><li><a href="/glossary#persistent-absence">persistent absence</a></li><li><a href="/glossary#unauthorised-absence">unauthorised absence</a></li></ul>'),
(NEWID(), GETUTCDATE(), @bau1UserId, 'Academic year', 'academic-year', N'<p>Lasts from 1 August to 31 July. Generally broken into 3 terms - autumn, spring and summer.</p><p>Throughout the service this is shown in the format ‘2012/13’ to describe the year from 1 August 2012 to 31 July 2013</p>'),
(NEWID(), GETUTCDATE(), @bau1UserId, 'Ad hoc statistics', 'ad-hoc-statistics', N'<p>Releases of statistics which are not part of DfE''s regular annual official statistical release calendar.</p>'),
(NEWID(), GETUTCDATE(), @bau1UserId, 'Advanced Learner Loan (ALL)', 'advanced-learner-loan-all', N'<p>Releases of statistics which are not part of DfE''s regular annual official statistical release calendar.</p>'),
(NEWID(), GETUTCDATE(), @bau1UserId, 'Authorised absence', 'authorised-absence', N'<p>When a pupil misses (or is absent from) at least 1 possible school session with the permission of a teacher or other authorised school representative.</p><p>Counted in sessions, where 1 session is equivalent to half-a-day.</p>'),
-- B
-- C
(NEWID(), GETUTCDATE(), @bau1UserId, 'Cancelled loans', 'cancelled-loans', N'<p>The borrower no longer has any liability to repay as provided for in the loans regulations. A borrower’s liability is cancelled:</p><ul><li>On the death of the borrower;</li><li>On reaching the age or length of time cancellation criteria for their loan (which varies by loan product); or,</li><li>If borrower is in receipt of a disability related benefit and permanently unfit for work.</li><li>Borrowers who study Access to HE courses and complete a higher education course have any outstanding ALLs balance written off.</li></ul>'),
(NEWID(), GETUTCDATE(), @bau1UserId, 'Capitalised interest', 'capitalised-interest', N'<p>The interest accrued on student loans is added to a borrower’s loan balance, rather than requiring repayment at the time it is accrued.</p>'),
(NEWID(), GETUTCDATE(), @bau1UserId, 'Care leaver', 'care-leaver', N'<p>Care leavers are relevant or former relevant children. Relevant children are defined under Section 23A(2) of the Children Act 1989 and former relevant children are defined under Section 23C (1) of the Children Act 1989.</p><p>A relevant child is:</p><ul><li>a young person aged 16 or 17</li><li>is no longer looked-after</li><li>before last ceasing to be looked-after, was an eligible child</li></ul><p>or</p><ul><li>a young person aged 16 or 17</li><li>not subject to a care order</li><li>detained, or in hospital on their 16th birthday</li><li>immediately before being detained or admitted to hospital had been looked-after for at least 13 weeks which began after they reached age 14.</li></ul><p>A former relevant child is one who is:</p><ul><li>aged 18 or above,</li></ul><p>and either</p><ul><li>has been a relevant child and would be one if he were under 18,</li></ul><p>or</p><ul><li>immediately before he ceased to be looked-after at age 18, was an eligible child.</li></ul>'),
(NEWID(), GETUTCDATE(), @bau1UserId, 'Child in need', 'child-in-need', N'<p>A child in need is defined under the Children Act 1989 as a child who is unlikely to reach or maintain a satisfactory level of health or development, or their health or development will be significantly impaired without the provision of children''s social care services, or the child is disabled.</p>'),
(NEWID(), GETUTCDATE(), @bau1UserId, 'Child protection plan', 'child-protection-plan', N'<p>A <a href="/glossary#child-in-need">child in need</a> becomes the subject of a child protection plan if they are assessed as being at risk of harm, at an initial child protection conference.</p>'),
(NEWID(), GETUTCDATE(), @bau1UserId, 'CLA', 'cla', N'<p>See <a href="/glossary#looked-after-child">Looked-after child</a></p>'),
-- D
(NEWID(), GETUTCDATE(), @bau1UserId, 'Delivered or dispatched', 'delivered-or-dispatched', N'<p>The device has been dispatched from the storage facility or is in transit awaiting delivery on a date specified by the recipient. Shipments are running on a next business day delivery basis and two redelivery attempts are made before the delivery is returned.</p>'),
(NEWID(), GETUTCDATE(), @bau1UserId, 'Device', 'device', N'<p>A laptop or tablet along with a protective sleeve and software/operating licences.</p>'),
(NEWID(), GETUTCDATE(), @bau1UserId, 'Disadvantaged pupils', 'disadvantaged-pupils', N'<p>Pupils who are one of the following:</p><ul><li>eligible for Free School Meals in the last 6 years (eligibility on census day)</li><li>looked after continuously for 1 day or more and aged 4-15</li><li>adopted from care</p></ul><p>This excludes children looked after under an agreed series of short-term placements.</p>'),
(NEWID(), GETUTCDATE(), @bau1UserId, 'Doctoral loan', 'doctoral-loan', N'<p>Loans issued to students on doctoral courses, on the Plan 3 repayment system. They are paid directly to students and can be used to cover fees or living costs.</p>'),
(NEWID(), GETUTCDATE(), @bau1UserId, 'Domicile', 'domicile', N'<p>The usual residence of a student in the period prior to commencement of study. Wherever ‘EU-domiciled’ students are referred to this includes students domiciled in countries other than the UK that count as EU-domiciled for funding purposes.</p>'),
(NEWID(), GETUTCDATE(), @bau1UserId, 'Dual main registered pupils', 'dual-main-registered-pupils', N'<p>Dual registered pupils who are enrolled at more than 1 school have a dual main registration (at their main school) and 1 or more subsidiary registrations (at their additional schools).</p><p>See also <a href="/glossary#dual-registered-pupils">dual registered pupils</a>.</p>'),
(NEWID(), GETUTCDATE(), @bau1UserId, 'Dual registered pupils', 'dual-registered-pupils', N'<p>Pupils who are enrolled at more than 1 school.</p><p>See also <a href="/glossary#dual-main-registered-pupils">dual main registered pupils</a>.</p>'),
-- E
(NEWID(), GETUTCDATE(), @bau1UserId, 'EAL', 'eal', N'<p>English as an Additional Language (EAL) refers to pupils whose first language is not English.</p>'),
(NEWID(), GETUTCDATE(), @bau1UserId, 'English devolved area', 'english-devolved-area', N'<p>Used to refer to combined authorities, mayoral combined authorities, and the Greater London Authority. Full list of authorities included below:</p><p>Mayoral combined authorities</p><ul><li>Cambridgeshire and Peterborough</li><li>Greater Manchester</li><li>Liverpool City Region</li><li>North of Tyne</li><li>Sheffield City Region</li><li>Tees Valley</li><li>West Midlands</li><li>West of England</li></ul><p>Non-mayoral combined authorities</p><ul><li>Great London Authority</li><li>North East</li><li>West Yorkshire</li></ul>'),
(NEWID(), GETUTCDATE(), @bau1UserId, 'Entrants', 'entrants', N'<p>Students in their first year of study. Defined as those starting a course in the academic year who have not been active at the same broad level of study at the same provider in either of the two previous academic years.</p>'),
(NEWID(), GETUTCDATE(), @bau1UserId, 'Exclusion', 'exclusion', N'<p>When a pupil is not allowed to attend (or is excluded from) a school.</p><p>There are 2 types of exclusion:</p><ul><li><a href="/glossary#fixed-period-exclusion">fixed-period exclusion</a></li><li><a href="/glossary#permanent-exclusion">permanent exclusion</a></li></ul>'),
(NEWID(), GETUTCDATE(), @bau1UserId, 'Exclusion rate', 'exclusion-rate', N'<p>The number of exclusions as a percentage of the overall school population.</p>'),
(NEWID(), GETUTCDATE(), @bau1UserId, 'Exclusion review panel', 'exclusion-review-panel', N'<p>The process by which parents (and pupils aged over 18 years) can request a review of a permanent exclusion.</p>'),
-- F
(NEWID(), GETUTCDATE(), @bau1UserId, 'Face value of loan book', 'face-value-of-loan-book', N'<p>The total outstanding balance on student loans. This will include all previous loan outlay and accrued interest, less any repayments or loan cancellations.</p>'),
(NEWID(), GETUTCDATE(), @bau1UserId, 'Financial year', 'financial-year', N'<p>The year from 1 April to 31 March. Throughout the service this is shown in the format ‘2012-13’ to describe the year from 1 April 2012 to 31 March 2013.</p>'),
(NEWID(), GETUTCDATE(), @bau1UserId, 'Fixed-period exclusion', 'fixed-period-exclusion', N'<p>When a pupil is not allowed to attend (or is excluded from) a school for a set period of time.</p><p>This can be for part of a school day and does not have to be for a continuous period.</p><p>A pupil can be excluded for 1 or more fixed periods up to a maximum of 45 school days in a single academic year.</p><p>This total includes exclusions from previous schools covered by the exclusion legislation so pupils with repeat exclusions can inflate fixed-period exclusion rates.</p>'),
(NEWID(), GETUTCDATE(), @bau1UserId, 'Fully repaid loan', 'fully-repaid-loan', N'<p>The borrower has repaid the loan in full during their repayment term without it being cancelled.</p>'),
-- G
-- H
(NEWID(), GETUTCDATE(), @bau1UserId, 'Higher education full-time loan', 'higher-education-full-time-loan', N'<p>Loans available to students on full-time higher education courses, including first degrees, sub-degrees and certain postgraduate courses (e.g. Postgraduate Certificate in Education or PGCEs) that are eligible for the undergraduate loan system.</p>'),
(NEWID(), GETUTCDATE(), @bau1UserId, 'Higher education part-time loan', 'higher-education-part-time-loan', N'<p>Loans available to students on part-time higher education courses with an intensity of 25% or higher.</p>'),
(NEWID(), GETUTCDATE(), @bau1UserId, 'Household Residual Income', 'household-residual-income', N'<p>The household gross income minus payments to private pension schemes, additional voluntary contributions and employment related costs as well as allowances for dependents and students.</p>'),
-- I
(NEWID(), GETUTCDATE(), @bau1UserId, 'Income Contingent Repayment (ICR) loan', 'income-contingent-repayment-icr-loan', N'<p>Loans for which the required repayments are based on the borrower’s income. The type of student loan that has been available to students since 1998.</p>'),
(NEWID(), GETUTCDATE(), @bau1UserId, 'Independent review panel', 'independent-review-panel', N'<p>Parents (and pupils if aged over 18 years) can request a review of a permanent exclusion.</p><p>An independent review panel’s role is to review the decision of the governing body not to reinstate a permanently excluded pupil.</p><p>It must consider the interests and circumstances of the excluded pupil, including the circumstances in which the pupil was excluded, and have regard to the interests of other pupils and people working at the school.</p>'),
-- J
-- K
-- L
(NEWID(), GETUTCDATE(), @bau1UserId, 'LAEstab', 'laestab', N'<p>Local authority establishment, a 7 digit code created by Department for Education. Consists of a 3-digit local authority code, followed by a 4-digit establishment code.</p>'),
(NEWID(), GETUTCDATE(), @bau1UserId, 'Liable to make repayments', 'liable-to-make-repayments', N'<p>The borrower has a remaining loan balance and has reached their Statutory Repayment Due Date (SRDD).</p>'),
(NEWID(), GETUTCDATE(), @bau1UserId, 'Looked-after-child', 'looked-after-child', N'<p>Under the Children Act 1989, a child is looked-after by a local authority if he or she falls into one of the following:</p><ul><li>is provided with accommodation, for a continuous period of more than 24 hours [Children Act 1989, Section 20 and 21]</li><li>is subject to a care order [Children Act 1989, Part IV]</li><li>is subject to a placement order</li></ul>'),
(NEWID(), GETUTCDATE(), @bau1UserId, 'Lunchtime exclusion', 'lunchtime-exclusion', N'<p>When a pupil is not allowed to attend (or is excluded from) a school for the duration of the school''s lunchtime period.</p><p>A pupil is excluded in this way when their lunchtime behaviour has been disruptive.</p>'),
-- M
(NEWID(), GETUTCDATE(), @bau1UserId, 'Maintenance loan', 'maintenance-loan', N'<p>Maintenance loans are loans to cover living costs, paid directly to the student.</p>'),
(NEWID(), GETUTCDATE(), @bau1UserId, 'Master''s loan', 'master-s-loan', N'<p>Loans issued to students on master’s courses, on the Plan 3 repayment system. They are paid directly to students and can be used to cover fees or living costs.</p>'),
-- N
(NEWID(), GETUTCDATE(), @bau1UserId, 'National Offer Day', 'national-offer-day', N'<p>The day when councils send parents confirmations of their child''s place at school.</p><p>Primary school places are confirmed on 16 April each year - known as National Primary Offer Day.</p><p>Secondary school places are confirmed on 1 March each year - known as National Secondary Offer Day.</p><p>If either date falls on a weekend, confirmations are sent the next working day.</p>'),
(NEWID(), GETUTCDATE(), @bau1UserId, 'National Statistician', 'national-statistician', N'<p>Chief Executive of the UK Statistics Authority (UKSA) and the Head of the UK Government Statistical Service (GSS).</p><p>More information on the current National Statistician can be found on the <a href="https://gss.civilservice.gov.uk/about-us/national-statistician/" target="_blank" rel="noopener noreferrer">GSS website</a></p>'),
-- O
(NEWID(), GETUTCDATE(), @bau1UserId, 'One or more fixed-period exclusion', 'one-or-more-fixed-period-exclusion', N'<p>Pupils who have had at least 1 fixed-period exclusions across a full academic year.</p><p>Includes those with repeated fixed-period exclusions.</p>'),
(NEWID(), GETUTCDATE(), @bau1UserId, 'Open data', 'open-data', N'<p>Open data is data that anyone can access, use and share.</p><p>All of our data files are released under the terms of the <a href="http://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/" target="_blank" rel="noopener noreferrer">Open Government License</a> and are designed to meet at least 3 stars for <a href="https://www.gov.uk/government/publications/2010-to-2015-government-policy-government-transparency-and-accountability/2010-to-2015-government-policy-government-transparency-and-accountability#appendix-3-releasing-data-in-open-and-anonymised-formats" target="_blank" rel="noopener noreferrer">Government Open Data</a>.</p>'),
(NEWID(), GETUTCDATE(), @bau1UserId, 'Otherwise vulnerable', 'otherwise-vulnerable', N'<p>Children and young people might be identified as ‘otherwise vulnerable’, falling in to the category of vulnerable children and young people, if education providers or local authorities (including children’s social care services) identify them as such. These groups of students could therefore benefit from continued full-time attendance during the coronavirus pandemic.</p><p>Examples of why a student might be identified as otherwise vulnerable include:</p><ul><li>children and young people on the edge of receiving support from children’s social care services or in the process of being referred to children’s services</li><li>adopted children or children on a special guardianship order</li><li>those at risk of becoming NEET (‘not in employment, education or training’)</li><li>those living in temporary accommodation</li><li>those who are young carers</li><li>those who may have difficulty engaging with remote education at home (for example due to a lack of devices or quiet space to study)</li><li>care leavers</li><li>others at the provider and local authority’s discretion including pupils and students who need to attend to receive support or manage risks to their mental health</li><li>those who may have difficulty engaging with remote education at home (for example, due to a lack of devices or quiet space to study)</li></ul><p>Further guidance can be found in the document: <a href="https://www.gov.uk/government/publications/coronavirus-covid-19-maintaining-educational-provision/guidance-for-schools-colleges-and-local-authorities-on-maintaining-educational-provision#vulnerable-children-and-young-people" target="_blank" rel="noopener noreferrer">Guidance - children of critical workers and vulnerable children who can access schools or educational settings</a>.</p>'),
(NEWID(), GETUTCDATE(), @bau1UserId, 'Overall absence', 'overall-absence', N'<p>The total number of all authorised and unauthorised absences from possible school sessions for all pupils.</p><p>Expressed as a percentage of the total number of possible school sessions for all pupils.</p><p>Counted in sessions, where 1 session is equivalent to half-a-day.</p>'),
-- P
(NEWID(), GETUTCDATE(), @bau1UserId, 'Permanent exclusion', 'permanent-exclusion', N'<p>When a pupil is not allowed to attend (or is excluded from) a school and cannot go back to that specific school unless their exclusion is overturned.</p>'),
(NEWID(), GETUTCDATE(), @bau1UserId, 'Persistent absence', 'persistent-absence', N'<p>When a pupil misses (or is absent from) 10% or more possible school sessions.</p><p>Counted in sessions, where 1 session is equivalent to half-a-day.</p><p>This definition changed at the start of the 2015/16 academic year.</p><p>For further information on this change read our <a href="/methodology/pupil-absence-in-schools-in-england">Pupil absence statistics: methodology</a> guidance.</p>'),
(NEWID(), GETUTCDATE(), @bau1UserId, 'Plans 1, 2 and 3', 'plan-1-2-and-3', N'<p>The ICR loan scheme has been separated into different repayment arrangements called Plans 1, 2 and 3. While they operate in a similar manner, they differ in some ways such as the repayment thresholds, interest rates and the length of borrowers’ repayment terms.</p><p>Plan 1 is the loan system for undergraduate students that started courses before September 2012, Plan 2 the system for undergraduates since September 2012 and for Advanced Learner Loans, and Plan 3 the system for postgraduate loans introduced in 2016.</p>'),
(NEWID(), GETUTCDATE(), @bau1UserId, 'Possible school session', 'possible-school-session', N'<p>Schools are required to provide 2 possible sessions per day - 1 session in the morning and 1 in the afternoon.</p><p>This is why a session is equivalent to half-a-day.</p>'),
(NEWID(), GETUTCDATE(), @bau1UserId, 'Pupil enrolment', 'pupil-enrolment', N'<p>A way to refer to a ''pupil'' at a school. The number of pupil enrolments presented includes pupils on the school roll for at least 1 session who are aged between 5 and 15 years, excluding boarders.</p><p>Some pupils may be counted more than once. For example, if they moved schools during the academic year or are registered in more than 1 school.</p>'),
(NEWID(), GETUTCDATE(), @bau1UserId, 'Pupil referral unit (PRUs)', 'pupil-referral-unit', N'<p>An alternative education provision specifically organised to provide education for children who are not able to attend school and may not otherwise receive a suitable education.</p><p>This could be because they have a short- or long-term illness, have been excluded from school or are a new starter waiting for a mainstream school place.</p><p>Under section 19 of the Education Act 1996, each local education authority (LEA) has a duty to provide suitable education for children of compulsory school age who cannot attend school.</p><p>Placing pupils in PRUs is one of the ways in which LEAs can make sure they can comply with this duty.</p><p>PRUs are a mixture of public units and privately managed companies.</p>'),
(NEWID(), GETUTCDATE(), @bau1UserId, 'Pupils with one or more fixed-period exclusion', 'pupils-with-1-or-more-fixed-period-exclusion', N'<p>Pupil who have had at least one fixed-period exclusion across a full academic year.</p>'),
-- Q
-- R
(NEWID(), GETUTCDATE(), @bau1UserId, 'Repayment term', 'repayment-term', N'<p>The period for which a loan borrower is liable to make repayments based on their income. At the end of a borrowers’ repayment term any remaining loan balance is cancelled.</p>'),
(NEWID(), GETUTCDATE(), @bau1UserId, 'Repayment threshold', 'repayment-threshold', N'<p>The annual income threshold above which borrowers are required to make repayments on any eligible income. Plan 1 and Plan 2 loan borrowers are required to pay 9% of any earnings above the threshold and Plan 3 borrowers will be required to repay 6%.</p>'),
(NEWID(), GETUTCDATE(), @bau1UserId, 'Resource Account Budgeting (RAB) charge', 'resource-account-budgeting-rab-charge', N'<p>Used in the DfE annual accounts, this is the proportion of loan outlay that is expected to not be repaid when future repayments are valued in present terms.</p>'),
(NEWID(), GETUTCDATE(), @bau1UserId, 'Respite care', 'respite-care', N'<p>Short-term break agreements, which are short periods of care for a child provided by the local authority in order to give the parents or guardians some respite from the normal duties of looking after the child. Each break must include at least one night away from home but cannot exceed 17 days of continuous care. Also referred to as shared care; or family link placements.</p>'),
-- S
(NEWID(), GETUTCDATE(), @bau1UserId, 'School census', 'school-census', N'<p>Statutory termly data collection for all of the following educational organisations in England:</p><ul><li>academies - including free schools and studio schools</li><li>colleges - including city technology and university technical colleges</li><li>maintained schools - including nurseries, middle-deemed primary and secondary schools, primary schools and secondary schools</li><li>special schools - including local authority maintained and non-maintained special schools</li></ul>'),
(NEWID(), GETUTCDATE(), @bau1UserId, 'School session', 'school-session', N'<p>See <a href="/glossary#possible-school-session">possible school session</a></p>'),
(NEWID(), GETUTCDATE(), @bau1UserId, 'School year', 'school-year', N'<p>See <a href="/glossary#academic-year">academic year</a></p>'),
(NEWID(), GETUTCDATE(), @bau1UserId, 'Secure children''s home', 'secure-childrens-home', N'<p>Children''s homes which provide a locked environment and restrict a child or young person''s liberty.</p><p>They provide care and accommodation to children and young people who have been detained or sentenced by the criminal courts and those who have been remanded to secure local authority accommodation. They also accommodate and care for children and young people who have been placed there on welfare grounds by local authorities and the courts.</p>'),
(NEWID(), GETUTCDATE(), @bau1UserId, 'Self-isolating pupils', 'self-isolating-pupils', N'<p>Pupils self-isolating due to potential contact with a case of coronavirus inside or outside the school.</p>'),
(NEWID(), GETUTCDATE(), @bau1UserId, 'Sole registered pupils', 'sole-registered-pupils', N'<p>Pupils who are on the roll of only 1 school.</p>'),
(NEWID(), GETUTCDATE(), @bau1UserId, 'SSDA903', 'ssda903', N'<p>The annual child level data collection returned by local authorities in England, covering children looked after. Also referred to as the CLA data collection.</p>'),
(NEWID(), GETUTCDATE(), @bau1UserId, 'State-funded schools', 'state-funded-schools', N'<p>Includes primary, secondary, special schools and alternative provision. Further education colleges, post-16 special institutions and independent schools are not included in these figures.</p>'),
(NEWID(), GETUTCDATE(), @bau1UserId, 'Statutory Repayment Due Date (SRDD)', 'statutory-repayment-duedate-SRDD', N'<p>The point a borrower becomes liable to begin repaying a loan, normally the start of the tax year (6 April) after graduating or otherwise leaving their course. After the SRDD borrowers are required to make repayments if their income is above the repayment threshold.</p>'),
(NEWID(), GETUTCDATE(), @bau1UserId, 'Stock charge', 'stock-charge', N'<p>This is the proportion of the total outstanding face value of loans that is expected to not be repaid when future repayments are valued in present terms.</p>'),
-- T
(NEWID(), GETUTCDATE(), @bau1UserId, 'Tax year', 'tax-year', N'<p>The 12-month period starting on 6 April.</p>'),
(NEWID(), GETUTCDATE(), @bau1UserId, 'Tuition fee loan', 'tuition-fee-loan', N'<p>Tuition fee loans are loans to cover all or part of the cost of tuition. They are paid directly to the learning provider.</p>'),
-- U
(NEWID(), GETUTCDATE(), @bau1UserId, 'UKPRN', 'ukprn', N'<p>United Kingdom provider reference number. A unique reference number issued by the <a href="https://www.ukrlp.co.uk/" target="_blank" rel="noopener noreferrer">UK Register of Learning Providers</a> after a successful registration. This is an 8-digit number that always starts with a 1.</p>'),
(NEWID(), GETUTCDATE(), @bau1UserId, 'URN', 'urn', N'<p>The URN is a sequential and unique number automatically assigned by the DfE’s <a href="https://www.get-information-schools.service.gov.uk/" target="_blank" rel="noopener noreferrer">Get Information about Schools (GIAS)</a> system when a record is created.</p><p>For Children centres these are 5 digits long and start with a 2. Welsh establishments are 6 digits long and start with a 4. All other establishments are 6 digits long and start with a 1.</p>'),
(NEWID(), GETUTCDATE(), @bau1UserId, 'Unaccompanied asylum-seeking child (UASC)', 'unaccompanied-asylum-seeking-child', N'<p>Children aged under 18, who have applied for asylum in their own right and are separated from both parents and/or any other responsible adult. Local authorities have a legal duty to provide accommodation for these children.</p>'),
(NEWID(), GETUTCDATE(), @bau1UserId, 'Unauthorised absence', 'unauthorised-absence', N'<p>When a pupil misses at least 1 possible school session without the permission of a teacher or other authorised school representative.</p><p>Includes all unexplained or unjustified absences and late arrivals.</p><p>Counted in sessions, where 1 session is equivalent to half-a-day.</p>'),
-- V
(NEWID(), GETUTCDATE(), @bau1UserId, 'Voluntary repayment', 'voluntary-repayment', N'<p>A borrower can at any time choose to repay some or all of their loan balance early, in addition to any repayments they are liable to make based on their income.</p>');
-- W
-- X
-- Y
-- Z
