DROP INDEX [IX_DataImports_FileId] ON [dbo].[DataImports]

CREATE UNIQUE NONCLUSTERED INDEX [IX_DataImports_FileId] ON [dbo].[DataImports]
(
[FileId] ASC
)
INCLUDE([Status])
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]