REVOKE ALL ON [dbo].[Comment] TO [importer];
REVOKE ALL ON [dbo].[Contacts] TO [importer];
REVOKE ALL ON [dbo].[ContentBlock] TO [importer];
REVOKE ALL ON [dbo].[ContentSections] TO [importer];
REVOKE ALL ON [dbo].[DataImports] TO [importer];
REVOKE ALL ON [dbo].[DataImportErrors] TO [importer];
REVOKE ALL ON [dbo].[DataSetFileVersionGeographicLevels] TO [importer];
REVOKE ALL ON [dbo].[DataSetMappings] TO [importer];
REVOKE ALL ON [dbo].[ExternalMethodology] TO [importer];
REVOKE ALL ON [dbo].[Files] TO [importer];
REVOKE ALL ON [dbo].[GlossaryEntries] TO [importer];
REVOKE ALL ON [dbo].[Methodologies] TO [importer];
REVOKE ALL ON [dbo].[MethodologyFiles] TO [importer];
REVOKE ALL ON [dbo].[MethodologyNotes] TO [importer];
REVOKE ALL ON [dbo].[MethodologyVersions] TO [importer];
REVOKE ALL ON [dbo].[Permalinks] TO [importer];
REVOKE ALL ON [dbo].[PublicationMethodologies] TO [importer];
REVOKE ALL ON [dbo].[Publications] TO [importer];
REVOKE ALL ON [dbo].[ReleaseFiles] TO [importer];
REVOKE ALL ON [dbo].[Releases] TO [importer];
REVOKE ALL ON [dbo].[ReleaseVersions] TO [importer];
REVOKE ALL ON [dbo].[ReleaseStatus] TO [importer];
REVOKE ALL ON [dbo].[Themes] TO [importer];
REVOKE ALL ON [dbo].[Update] TO [importer];

GRANT SELECT, INSERT, UPDATE ON [dbo].[DataImports] TO [importer];
GRANT SELECT, INSERT, UPDATE ON [dbo].[DataImportErrors] TO [importer];
GRANT SELECT, INSERT, UPDATE ON [dbo].[DataSetFileVersionGeographicLevels] TO [importer];
GRANT INSERT ON [dbo].[DataSetMappings] TO [importer];
GRANT SELECT, UPDATE ON [dbo].[Files] TO [importer];