REVOKE ALL ON [dbo].[Comment] TO [publisher];
REVOKE ALL ON [dbo].[Contacts] TO [publisher];
REVOKE ALL ON [dbo].[ContentBlock] TO [publisher];
REVOKE ALL ON [dbo].[ContentSections] TO [publisher];
REVOKE ALL ON [dbo].[DataBlocks] TO [publisher];
REVOKE ALL ON [dbo].[DataBlockVersions] TO [publisher];
REVOKE ALL ON [dbo].[DataSetFileVersionGeographicLevels] TO [publisher];
REVOKE ALL ON [dbo].[DataImports] TO [publisher];
REVOKE ALL ON [dbo].[DataImportErrors] TO [publisher];
REVOKE ALL ON [dbo].[EinContentBlocks] TO [publisher];
REVOKE ALL ON [dbo].[EinContentSections] TO [publisher];
REVOKE ALL ON [dbo].[EinPages] TO [publisher];
REVOKE ALL ON [dbo].[EinPageVersions] TO [publisher];
REVOKE ALL ON [dbo].[EinTiles] TO [publisher];
REVOKE ALL ON [dbo].[EmbedBlocks] TO [publisher];
REVOKE ALL ON [dbo].[ExternalMethodology] TO [publisher];
REVOKE ALL ON [dbo].[FeaturedTables] TO [publisher];
REVOKE ALL ON [dbo].[Files] TO [publisher];
REVOKE ALL ON [dbo].[GlossaryEntries] TO [publisher];
REVOKE ALL ON [dbo].[KeyStatistics] TO [publisher];
REVOKE ALL ON [dbo].[KeyStatisticsDataBlock] TO [publisher];
REVOKE ALL ON [dbo].[KeyStatisticsText] TO [publisher];
REVOKE ALL ON [dbo].[Methodologies] TO [publisher];
REVOKE ALL ON [dbo].[MethodologyFiles] TO [publisher];
REVOKE ALL ON [dbo].[MethodologyNotes] TO [publisher];
REVOKE ALL ON [dbo].[MethodologyRedirects] TO [publisher];
REVOKE ALL ON [dbo].[MethodologyVersions] TO [publisher];
REVOKE ALL ON [dbo].[Organisations] TO [publisher];
REVOKE ALL ON [dbo].[Permalinks] TO [publisher];
REVOKE ALL ON [dbo].[PublicationMethodologies] TO [publisher];
REVOKE ALL ON [dbo].[Publications] TO [publisher];
REVOKE ALL ON [dbo].[PublicationRedirects] TO [publisher];
REVOKE ALL ON [dbo].[ReleasePublishingFeedback] TO [publisher];
REVOKE ALL ON [dbo].[ReleaseFiles] TO [publisher];
REVOKE ALL ON [dbo].[Releases] TO [publisher];
REVOKE ALL ON [dbo].[ReleaseStatus] TO [publisher];
REVOKE ALL ON [dbo].[ReleaseRedirects] TO [publisher];
REVOKE ALL ON [dbo].[ReleaseVersionPublishingOrganisations] TO [publisher];
REVOKE ALL ON [dbo].[ReleaseVersions] TO [publisher];
REVOKE ALL ON [dbo].[Themes] TO [publisher];
REVOKE ALL ON [dbo].[Update] TO [publisher];
REVOKE ALL ON [dbo].[UserPublicationRoles] TO [publisher];
REVOKE ALL ON [dbo].[Users] TO [publisher];


GRANT SELECT, UPDATE ON [dbo].[ContentBlock] TO [publisher];
GRANT SELECT ON [dbo].[ContentSections] TO [publisher];
GRANT SELECT, UPDATE ON [dbo].[DataBlocks] TO [publisher];
GRANT SELECT, UPDATE ON [dbo].[DataBlockVersions] TO [publisher];
GRANT SELECT ON [dbo].[DataSetFileVersionGeographicLevels] TO [publisher];
GRANT SELECT ON [dbo].[EinContentBlocks] TO [publisher];
GRANT SELECT ON [dbo].[EinContentSections] TO [publisher];
GRANT SELECT ON [dbo].[EinPages] TO [publisher];
GRANT SELECT ON [dbo].[EinPageVersions] TO [publisher];
GRANT SELECT, UPDATE ON [dbo].[EinTiles] TO [publisher];
GRANT SELECT ON [dbo].[EmbedBlocks] TO [publisher];
GRANT SELECT ON [dbo].[ExternalMethodology] TO [publisher];
GRANT SELECT ON [dbo].[FeaturedTables] TO [publisher];
GRANT SELECT ON [dbo].[Files] TO [publisher];
GRANT SELECT ON [dbo].[KeyStatistics] TO [publisher];
GRANT SELECT ON [dbo].[KeyStatisticsDataBlock] TO [publisher];
GRANT SELECT ON [dbo].[KeyStatisticsText] TO [publisher];
GRANT SELECT, UPDATE ON [dbo].[Methodologies] TO [publisher];
GRANT SELECT ON [dbo].[MethodologyFiles] TO [publisher];
GRANT SELECT, UPDATE ON [dbo].[MethodologyVersions] TO [publisher];
GRANT SELECT ON [dbo].[MethodologyRedirects] TO [publisher];
GRANT SELECT ON [dbo].[Organisations] TO [publisher];
GRANT SELECT, UPDATE ON [dbo].[Publications] TO [publisher];
GRANT SELECT ON [dbo].[PublicationRedirects] TO [publisher];
GRANT SELECT ON [dbo].[PublicationMethodologies] TO [publisher];
GRANT SELECT ON [dbo].[Releases] TO [publisher];
GRANT SELECT, UPDATE ON [dbo].[ReleaseFiles] TO [publisher];
GRANT SELECT, INSERT ON [dbo].[ReleasePublishingFeedback] TO [publisher];
GRANT SELECT ON [dbo].[ReleaseRedirects] TO [publisher];
GRANT SELECT ON [dbo].[ReleaseVersionPublishingOrganisations] TO [publisher];
GRANT SELECT, UPDATE ON [dbo].[ReleaseVersions] TO [publisher];
GRANT SELECT ON [dbo].[Themes] TO [publisher];
GRANT SELECT ON [dbo].[Update] TO [publisher];
GRANT SELECT ON [dbo].[UserPublicationRoles] TO [publisher];
GRANT SELECT ON [dbo].[Users] TO [publisher];