trigger: none

resources:
  pipelines:
    - pipeline: EESBuildPipeline
      source: Explore Education Statistics
      trigger: true

# This defines the "Build.BuildNumber" variable available in the pipeline.
name: $(Date:yyyyMMdd).$(Rev:r)

parameters:
  - name: psqlDbUsersAdded
    displayName: Have database users been added to PSQL yet for Container App and Function App?
    default: true

variables:
  - group: EES Bicep Infrastructure common
  - name: isDev
    value: $[eq(variables['Build.SourceBranch'], 'refs/heads/EES-4807-build-and-deploy-function-app')]
  - name: isDev
    value: $[eq(variables['Build.SourceBranch'], 'refs/heads/test')]
  - name: isMaster
    value: $[eq(variables['Build.SourceBranch'], 'refs/heads/master')]
  - name: vmImageName
    value: 'ubuntu-latest'
  - name: templateDirectory
    value: $(Build.SourcesDirectory)/infrastructure/templates/public-api
  - name: templateFile
    value: $(templateDirectory)/main.bicep
  - name: paramDirectory
    value: $(templateDirectory)/parameters
  - name: devParamFile
    value: $(paramDirectory)/main-dev.bicepparam
  - name: testParamFile
    value: $(paramDirectory)/main-test.bicepparam
  - name: preProdParamFile
    value: $(paramDirectory)/main-preprod.bicepparam
  - name: prodParamFile
    value: $(paramDirectory)/main-prod.bicepparam
  - name: upstreamPipelineBuildNumber
    value: $(resources.pipeline.EESBuildPipeline.runName)
  - name: psqlDbUsersAdded
    value: ${{parameters.psqlDbUsersAdded}}

pool:
  #  vmImage: $(vmImageName)
  name: dfe-development-dw agent pool

stages:
- ${{ if variables.isDev }}:
#  - template: validate-stage-template.yml
#    parameters:
#      stageName: 'Validate_Against_Development'
#      environment: 'Development'
#      serviceConnection: $(serviceConnectionDevelopment)

  - template: deploy-stage-template.yml
    parameters:
      stageName: 'Deploy_to_Development'
      environment: 'Development'
      serviceConnection: $(serviceConnectionDevelopment)
#      dependsOn: 'Validate_Against_Development'

- ${{ if variables.isTest }}:
  - template: validate-stage-template.yml
    parameters:
      stageName: 'Validate_Against_Test'
      environment: 'Test'
      serviceConnection: $(serviceConnectionTest)

  - template: deploy-stage-template.yml
    parameters:
      stageName: 'Deploy_to_Test'
      environment: 'Test'
      serviceConnection: $(serviceConnectionTest)
      dependsOn: 'Validate_Against_Test'

#  - template: deploy-stage-template.yml
#    parameters:
#      environment: 'Test'
#      dependsOn: DeployDevelopment
#      resourceGroupName: ${{parameters.resourceGroupName}}
#      psqlDbUsersAdded: ${{parameters.psqlDbUsersAdded}}
#
#- ${{ if eq(variables.isMaster, 'true') }}:
#  - template: deploy-stage-template.yml
#    parameters:
#      environment: 'PreProduction'
#      dependsOn: DeployDevelopment
#      resourceGroupName: ${{parameters.resourceGroupName}}
#      psqlDbUsersAdded: ${{parameters.psqlDbUsersAdded}}
#
#  - template: deploy-stage-template.yml
#    parameters:
#      environment: 'Production'
#      dependsOn: DeployPreProduction
#      resourceGroupName: ${{parameters.resourceGroupName}}
#      psqlDbUsersAdded: ${{parameters.psqlDbUsersAdded}}
