# This isa reusable Deploy stage definition that is parameterised to be reusable
# to support deployment to different environments

parameters:
  - name:
    default: 'Development'
  - name: dependsOn
    default: 'Build'
#  - name: resourceGroupName
#    default: 'dfe-dev-dw'
#  - name: psqlDbUsersAdded
#    default: true

stages:
- stage: Deploy${{parameters.environment}}
  displayName: 'Deploy to ${{parameters.environment}}'
  dependsOn: ${{parameters.dependsOn}}
  jobs:
  - deployment: Deploy
    displayName: 'Deploy ${{parameters.environment}} Infrastructure'
    environment: '${{parameters.environment}}'
    strategy:
      runOnce:
        deploy:
          steps:
          - download: none
          - checkout: self
          - task: AzureCLI@2
            displayName: 'Deploy bicep template to Azure'
            inputs:
              azureSubscription: $(serviceConnection)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                set -e
                az deployment group create \
                --resource-group ${{parameters.resourceGroupName}} \
                --template-file $(templateFile) \
                --parameters $(devParamFile) \
                --parameters \
                    resourceTags='$(resourceTags)' \
                    publicUrls='$(publicUrls)' \
                    postgreSqlAdminName='$(postgreSqlAdminName)' \
                    postgreSqlAdminPassword='$(postgreSqlAdminPassword)' \
                    dockerImagesTag='$(dockerImagesTag)' \
                    psqlDbUsersAdded=${{parameters.psqlDbUsersAdded}} \
                    dataProcessorZipFileUrl='${}'
