# This isa reusable Deploy stage definition that is parameterised to be reusable
# to support deployment to different environments

parameters:
  - name: environment
    default: 'Development'
  - name: dependsOn
    default: 'Build'
  - name: resourceGroupName
    default: 'dfe-devdw2'
  - name: psqlDbUsersAdded
    type: boolean
    default: true
  - name: dataProcessorZipFileUrl
    default: ''

stages:
- stage: Deploy${{parameters.environment}}
  displayName: 'Deploy to ${{parameters.environment}}'
  condition: succeeded()
  dependsOn: ${{parameters.dependsOn}}
  jobs:
#  - download: EESBuildPipeline
#    displayName: 'Download Data Processor Function App ZIP file'
#    artifact: data-processor
  - deployment: Deploy
    displayName: 'Deploy ${{parameters.environment}} Infrastructure'
    environment: '${{parameters.environment}}'
    strategy:
      runOnce:
        deploy:
          steps:
          - download: none
          - checkout: self
          - task: AzureCLI@2
            displayName: 'Deploy bicep template to Azure'
            inputs:
              azureSubscription: $(serviceConnection)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                set -e
                az deployment group create \
                --resource-group ${{parameters.resourceGroupName}} \
                --template-file $(templateFile) \
                --parameters $(devParamFile) \
                --parameters \
                    resourceTags='$(resourceTags)' \
                    publicUrls='$(publicUrls)' \
                    postgreSqlAdminName='$(postgreSqlAdminName)' \
                    postgreSqlAdminPassword='$(postgreSqlAdminPassword)' \
                    dockerImagesTag='$(dockerImagesTag)' \
                    psqlDbUsersAdded=${{parameters.psqlDbUsersAdded}} \
                    dataProcessorZipFileUrl='${{parameters.dataProcessorZipFileUrl}}'
