# This Step template extracts current values of fileshare settings from

parameters:
  - name: stepName
    type: string
  - name: serviceConnection
    type: string
  - name: functionAppName
    type: string
  - name: variableNamePrefix
    type: string

steps:
- task: AzureCLI@2
  displayName: ${{parameters.stepName}}
  inputs:
    azureSubscription: ${{parameters.serviceConnection}}
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      set -e
      functionAppExists=`az functionapp list --resource-group $(resourceGroupName) --subscription "$(subscription)"  --query "[?name=='${{parameters.functionAppName}}']" | jq '. != []'`
      functionAppProductionFileshare=''
      functionAppStagingFileshare=''
      
      if [ "$functionAppExists" = "true" ]; then
        functionAppProductionFileshare=`az functionapp config appsettings list --name ${{parameters.functionAppName}} --resource-group $(resourceGroupName) --subscription "$(subscription)" | jq '.[] | select ( .name == "WEBSITE_CONTENTSHARE" )' | jq -r '.value'`
        functionAppStagingFileshare=`az functionapp config appsettings list --name ${{parameters.functionAppName}} --resource-group $(resourceGroupName) --subscription "$(subscription)" --slot "staging" | jq '.[] | select ( .name == "WEBSITE_CONTENTSHARE" )' | jq -r '.value'`
      fi

      echo "##vso[task.setvariable variable=${{parameters.variableNamePrefix}}StagingFileshare;]$functionAppStagingFileshare"
      echo "##vso[task.setvariable variable=${{parameters.variableNamePrefix}}ProductionFileshare;]$functionAppProductionFileshare"
