# Workflow to block auto-squash commits (e.g. fixup, amend)
# from being merged in via pull requests.
# https://andrewlock.net/smoother-rebases-with-auto-squashing-git-commits/
name: Block auto-squash commits
on: pull_request
permissions:
  pull-requests: read
jobs:
  block-autosquash:
    name: Block auto-squash commits
    runs-on: ubuntu-latest
    steps:
      - name: Block auto-squash commits
        uses: xt0rted/block-autosquash-commits-action@f1ab4d69a90297fde61bc263d2e048eb8480d293
        with:
          repo-token: ${{ secrets.GH_TOKEN }}
